import { useEffect, useState } from 'react';
import { supabase } from '../../../lib/supabase';
import { Users, FolderKanban, UserPlus, CheckCircle2, XCircle, Clock3, Loader2, Star } from 'lucide-react';

type Application={id:string;full_name:string;email:string;phone:string;county:string;town:string;status:string;created_at:string};
export default function AdminDashboard(){
 const [stats,setStats]=useState({projects:0,messages:0,users:0,applications:0}); const [apps,setApps]=useState<Application[]>([]); const [loading,setLoading]=useState(true); const [processing,setProcessing]=useState<string|null>(null); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [p,m,u,a]=await Promise.all([supabase.from('projects').select('*',{count:'exact',head:true}),supabase.from('messages').select('*',{count:'exact',head:true}),supabase.from('profiles').select('*',{count:'exact',head:true}),supabase.from('connector_applications').select('id,full_name,email,phone,county,town,status,created_at').eq('status','pending').order('created_at',{ascending:false})]);if(p.error)throw p.error;if(m.error)throw m.error;if(u.error)throw u.error;if(a.error)throw a.error;setStats({projects:p.count||0,messages:m.count||0,users:u.count||0,applications:a.data?.length||0});setApps((a.data||[]) as Application[])}catch(e:any){console.error(e);setError(e?.message||'Unable to load the Admin workspace.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const process=async(id:string,status:'approved'|'rejected')=>{setProcessing(id);setError('');try{const {error}=await supabase.from('connector_applications').update({status,rejection_reason:status==='rejected'?'Rejected by Avelixa administration.':null,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;await load()}catch(e:any){setError(e?.message||`Unable to ${status} connector application.`)}finally{setProcessing(null)}};
 if(loading)return <div className="min-h-[50vh] flex items-center justify-center"><Loader2 className="w-7 h-7 animate-spin text-accent-400"/></div>;
 return <div className="space-y-10"><div><div className="text-xs font-bold uppercase tracking-widest text-accent-400">Administration</div><h1 className="mt-2 text-3xl font-light text-white">Admin Dashboard</h1><p className="mt-3 text-sm text-gray-400">Manage operations, reviews and Connector applications.</p></div>{error&&<div className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
 <div className="grid grid-cols-1 md:grid-cols-4 gap-4">{[['Projects',stats.projects,FolderKanban],['Messages',stats.messages,Star],['Users',stats.users,Users],['Pending Connectors',stats.applications,UserPlus]].map(([name,value,Icon]:any)=><div key={name as string} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><Icon className="w-5 h-5 text-accent-400"/><div className="mt-4 text-3xl text-white">{value as number}</div><div className="mt-1 text-xs uppercase tracking-widest text-gray-500">{name as string}</div></div>)}</div>
 <section><div className="flex items-center justify-between mb-5"><div><h2 className="text-xl font-medium text-white">Connector Applications</h2><p className="mt-1 text-sm text-gray-500">Admin and Owner can approve or reject pending Connectors.</p></div><div className="text-xs uppercase tracking-widest text-accent-400"><Clock3 className="inline w-4 h-4 mr-1"/>{apps.length} pending</div></div>{apps.length===0?<div className="rounded-2xl border border-white/10 p-8 text-center"><CheckCircle2 className="w-8 h-8 text-accent-400 mx-auto mb-3"/><p className="text-white">No pending Connector applications</p></div>:<div className="space-y-4">{apps.map(a=><div key={a.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5"><div><h3 className="text-white font-medium">{a.full_name}</h3><div className="mt-2 text-sm text-gray-400 space-y-1"><p>{a.email}</p><p>{a.phone}</p><p>{a.town}{a.town?', ':''}{a.county}</p></div><div className="mt-3 text-xs text-gray-600">Applied {new Date(a.created_at).toLocaleString()}</div></div><div className="flex gap-3"><button disabled={processing===a.id} onClick={()=>void process(a.id,'rejected')} className="inline-flex items-center gap-2 rounded-xl border border-red-500/20 px-4 py-3 text-sm text-red-300 disabled:opacity-50"><XCircle className="w-4 h-4"/>Reject</button><button disabled={processing===a.id} onClick={()=>void process(a.id,'approved')} className="inline-flex items-center gap-2 rounded-xl bg-accent-600 px-4 py-3 text-sm text-white disabled:opacity-50">{processing===a.id?<Loader2 className="w-4 h-4 animate-spin"/>:<CheckCircle2 className="w-4 h-4"/>}Approve</button></div></div></div>)}</div>}</section>
 <section><h2 className="text-xl font-medium text-white">Reviews</h2><p className="mt-1 text-sm text-gray-500">Approve or reject public reviews before they appear on Avelixa.</p><a href="/portal/reviews" className="inline-flex mt-4 rounded-xl border border-accent-500/20 bg-accent-500/5 px-4 py-3 text-sm text-accent-300">Open Review Moderation</a></section></div>;
}