import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { supabase } from '../../../lib/supabase';
import { FolderKanban, Users, WalletCards, ShieldCheck, ArrowRight, RefreshCw, ReceiptText, UserPlus, CheckCircle2, XCircle, Loader2, Star, Clock3, Link2, Save } from 'lucide-react';
type Application={id:string;full_name:string;email:string;phone:string;county:string;town:string;status:string;created_at:string}; type ReviewProject={id:string;title:string;status:string;updated_at:string};
type SiteLinks={whatsapp_number:string;instagram_url:string;facebook_url:string;email:string};
const defaultSiteLinks:SiteLinks={whatsapp_number:'254100601060',instagram_url:'https://www.instagram.com/avelixa_hq/',facebook_url:'https://www.facebook.com/share/1FJM6v5SfN/',email:'contact@avelixa.co.ke'};
export default function OwnerDashboard(){
 const [stats,setStats]=useState({projects:0,profiles:0,team:0,payouts:0,invoices:0,reviews:0}); const [apps,setApps]=useState<Application[]>([]); const [reviewProjects,setReviewProjects]=useState<ReviewProject[]>([]); const [loading,setLoading]=useState(true); const [processing,setProcessing]=useState<string|null>(null); const [error,setError]=useState('');
 const [siteLinks,setSiteLinks]=useState<SiteLinks>(defaultSiteLinks); const [savingLinks,setSavingLinks]=useState(false); const [linksMessage,setLinksMessage]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [p,c,t,po,i,a,r,s]=await Promise.all([supabase.from('projects').select('*',{count:'exact',head:true}),supabase.from('profiles').select('*',{count:'exact',head:true}),supabase.from('user_roles').select('user_id'),supabase.from('payouts').select('*',{count:'exact',head:true}).eq('status','pending'),supabase.from('invoices').select('*',{count:'exact',head:true}).neq('status','paid'),supabase.from('connector_applications').select('id,full_name,email,phone,county,town,status,created_at').eq('status','pending').order('created_at',{ascending:false}),supabase.from('projects').select('id,title,status,updated_at').eq('status','review').order('updated_at',{ascending:false}),supabase.from('settings').select('value').eq('key','site_contact_links').maybeSingle()]);for(const x of [p,c,t,po,i,a,r,s])if(x.error)throw x.error;setStats({projects:p.count||0,profiles:c.count||0,team:new Set((t.data||[]).map((x:any)=>x.user_id)).size,payouts:po.count||0,invoices:i.count||0,reviews:r.data?.length||0});setApps((a.data||[]) as Application[]);setReviewProjects((r.data||[]) as ReviewProject[]);if(s.data?.value)setSiteLinks({...defaultSiteLinks,...(s.data.value as Partial<SiteLinks>)})}catch(e:any){console.error(e);setError(e?.message||'Failed to load the Owner dashboard.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const update=async(table:string,id:string,status:string)=>{setProcessing(id);try{const {error}=await supabase.from(table).update({status,updated_at:new Date().toISOString(),...(table==='connector_applications'?{rejection_reason:status==='rejected'?'Rejected by Avelixa administration.':null}:{})}).eq('id',id);if(error)throw error;await load()}catch(e:any){setError(e?.message||'Update failed.')}finally{setProcessing(null)}};
 const saveLinks=async()=>{setSavingLinks(true);setLinksMessage('');setError('');try{const {error}=await supabase.from('settings').upsert({key:'site_contact_links',value:siteLinks,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error;setLinksMessage('Website links updated successfully.')}catch(e:any){setError(e?.message||'Unable to save website links.')}finally{setSavingLinks(false)}};
 const card=(title:string,description:string,path:string,Icon:any)=><Link to={path} className="group rounded-2xl border border-white/10 bg-white/[0.03] p-6 hover:border-accent-500/30 transition-all"><Icon className="w-6 h-6 text-accent-400"/><h3 className="mt-5 text-lg font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-gray-400">{description}</p><div className="mt-4 text-xs font-semibold uppercase tracking-widest text-accent-400">Open {title}<ArrowRight className="inline w-4 h-4 ml-2"/></div></Link>;
 return <div className="space-y-8"><div className="flex items-center justify-between"><div><div className="text-xs font-bold uppercase tracking-widest text-accent-400">Owner Command Center</div><h1 className="mt-2 text-3xl font-semibold text-white">Complete visibility and control</h1><p className="mt-2 text-sm text-gray-400">Owner controls remain separate from every other workspace.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm text-gray-200"><RefreshCw className={loading?'w-4 h-4 animate-spin':'w-4 h-4'}/>Refresh</button></div>{error&&<div className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
 <div className="grid grid-cols-2 lg:grid-cols-6 gap-4">{[['Projects',stats.projects,FolderKanban],['Profiles',stats.profiles,Users],['Team',stats.team,ShieldCheck],['Pending Payouts',stats.payouts,WalletCards],['Outstanding',stats.invoices,ReceiptText],['Reviews',stats.reviews,Clock3]].map(([n,v,I]:any)=><div key={n} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><I className="w-5 h-5 text-accent-400"/><div className="mt-4 text-3xl text-white">{loading?'—':v}</div><div className="mt-1 text-xs uppercase tracking-widest text-gray-500">{n}</div></div>)}</div>
 <div className="grid md:grid-cols-2 gap-5">{card('Finance','Track payments, invoices, commissions and payouts.','/portal/owner/finance',WalletCards)}{card('User Management','Manage Avelixa users and role assignments.','/portal/owner/users',ShieldCheck)}{card('Reviews','Approve or reject website reviews.','/portal/reviews',Star)}{card('Projects','Review operational projects.','/portal/admin/projects',FolderKanban)}</div>
 <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><div className="flex items-center gap-3"><Link2 className="w-5 h-5 text-accent-400"/><div><h2 className="text-xl font-medium text-white">Website Links</h2><p className="mt-1 text-sm text-gray-500">Owner-controlled public contact details. Changes are reflected on the website without editing code.</p></div></div>{linksMessage&&<div className="mt-4 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm text-emerald-300">{linksMessage}</div>}<div className="mt-5 grid md:grid-cols-2 gap-4">{([['instagram_url','Instagram URL'],['facebook_url','Facebook URL'],['whatsapp_number','WhatsApp number'],['email','Business email']] as const).map(([key,label])=><label key={key}><span className="block text-sm text-gray-300 mb-2">{label}</span><input value={siteLinks[key]} onChange={e=>setSiteLinks({...siteLinks,[key]:e.target.value})} className="w-full rounded-xl bg-ink-950 border border-ink-800 px-4 py-3 text-white outline-none focus:border-accent-500" /></label>)}</div><button onClick={()=>void saveLinks()} disabled={savingLinks} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-accent-600 px-5 py-3 text-white font-medium disabled:opacity-50">{savingLinks?<Loader2 className="w-4 h-4 animate-spin"/>:<Save className="w-4 h-4"/>Save Website Links</button></section>
 <section><h2 className="text-xl font-medium text-white">Project Reviews</h2><p className="mt-1 text-sm text-gray-500">Operators submit completed work here for Owner/Admin approval.</p>{reviewProjects.length===0?<div className="mt-4 rounded-2xl border border-white/10 p-8 text-center"><CheckCircle2 className="w-8 h-8 text-accent-400 mx-auto mb-3"/><p className="text-white">No projects awaiting review</p></div>:<div className="mt-4 space-y-4">{reviewProjects.map(p=><div key={p.id} className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-6"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><h3 className="text-white font-medium">{p.title}</h3><p className="mt-1 text-sm text-gray-400">Submitted for review · {new Date(p.updated_at).toLocaleString()}</p></div><div className="flex gap-3"><button disabled={processing===p.id} onClick={()=>void update('projects',p.id,'in_progress')} className="inline-flex items-center gap-2 rounded-xl border border-red-500/20 px-4 py-3 text-sm text-red-300"><XCircle className="w-4 h-4"/>Send Back</button><button disabled={processing===p.id} onClick={()=>void update('projects',p.id,'completed')} className="inline-flex items-center gap-2 rounded-xl bg-accent-600 px-4 py-3 text-sm text-white">{processing===p.id?<Loader2 className="w-4 h-4 animate-spin"/>:<CheckCircle2 className="w-4 h-4"/>}Approve</button></div></div></div>)}</div>}</section>
 <section><div className="flex items-center justify-between mb-5"><div><h2 className="text-xl font-medium text-white">Connector Applications</h2><p className="mt-1 text-sm text-gray-500">Owner and Admin are authorized to approve or reject Connectors.</p></div><div className="text-xs uppercase tracking-widest text-accent-400"><UserPlus className="inline w-4 h-4 mr-1"/>{apps.length} pending</div></div>{apps.length===0?<div className="rounded-2xl border border-white/10 p-8 text-center"><CheckCircle2 className="w-8 h-8 text-accent-400 mx-auto mb-3"/><p className="text-white">No pending Connector applications</p></div>:<div className="space-y-4">{apps.map(a=><div key={a.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5"><div><h3 className="text-white font-medium">{a.full_name}</h3><div className="mt-2 text-sm text-gray-400"><p>{a.email}</p><p>{a.phone}</p><p>{a.town}{a.town?', ':''}{a.county}</p></div></div><div className="flex gap-3"><button disabled={processing===a.id} onClick={()=>void update('connector_applications',a.id,'rejected')} className="inline-flex items-center gap-2 rounded-xl border border-red-500/20 px-4 py-3 text-sm text-red-300"><XCircle className="w-4 h-4"/>Reject</button><button disabled={processing===a.id} onClick={()=>void update('connector_applications',a.id,'approved')} className="inline-flex items-center gap-2 rounded-xl bg-accent-600 px-4 py-3 text-white">{processing===a.id?<Loader2 className="w-4 h-4 animate-spin"/>:<CheckCircle2 className="w-4 h-4"/>}Approve</button></div></div></div>)}</div>}</section></div>;
}