import { useState, useMemo, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppStore } from '../store';
import { Search, LayoutTemplate, Heart, Play, Palette, Layout } from 'lucide-react';
import { Template } from '../types';
import { TemplateRenderer } from '../components/template-engine/TemplateRenderer';

// A component to render a scaled-down real preview of the template
function TemplateThumbnail({ template }: { template: Template }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [scale, setScale] = useState(0.25);
  
  useEffect(() => {
    if (!containerRef.current) return;
    const observer = new ResizeObserver((entries) => {
      const containerWidth = entries[0].contentRect.width;
      setScale(containerWidth / 1440);
    });
    observer.observe(containerRef.current);
    return () => observer.disconnect();
  }, []);

  return (
    <div ref={containerRef} className="w-full aspect-[16/10] overflow-hidden relative bg-slate-100 flex flex-col pointer-events-none">
      {/* We scale down a 1440px wide viewport into the container */}
      <div 
        className="absolute top-0 left-0 origin-top-left"
        style={{
          width: '1440px',
          transform: `scale(${scale})`,
          height: `${100 / scale}%`,
        }}
      >
        <TemplateRenderer template={template} isPreview={true} />
      </div>
      
      {/* Fallback overlay gradient to fade out the bottom */}
      <div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-black/40 to-transparent z-10" />
    </div>
  );
}

export default function Gallery() {
  const navigate = useNavigate();
  const { templates, setCurrentTemplate, favorites, toggleFavorite } = useAppStore();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedIndustry, setSelectedIndustry] = useState<string>('All');
  const [selectedStyle, setSelectedStyle] = useState<string>('All');
  const [showFavoritesOnly, setShowFavoritesOnly] = useState(false);

  // Extract unique industries and styles
  const industries = useMemo(() => ['All', ...Array.from(new Set(templates.map(t => t.industry)))], [templates]);
  const styles = useMemo(() => ['All', ...Array.from(new Set(templates.map(t => t.style)))], [templates]);

  const filteredTemplates = templates.filter(t => {
    const matchesSearch = t.name.toLowerCase().includes(searchTerm.toLowerCase()) || t.industry.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesIndustry = selectedIndustry === 'All' || t.industry === selectedIndustry;
    const matchesStyle = selectedStyle === 'All' || t.style === selectedStyle;
    const matchesFavorites = showFavoritesOnly ? favorites.includes(t.id) : true;
    return matchesSearch && matchesIndustry && matchesStyle && matchesFavorites;
  });

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header Area */}
      <div className="bg-white border-b border-slate-200">
        <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-end mb-8 gap-6">
            <div className="max-w-2xl">
              <h1 className="text-4xl md:text-5xl font-bold text-slate-900 mb-4 tracking-tight">Explore Templates</h1>
              <p className="text-lg text-slate-600 leading-relaxed">Discover a curated collection of beautiful, functional website templates generated by AI. Find the perfect starting point for your next project.</p>
            </div>
            <button onClick={() => navigate('../wizard')} className="shrink-0 inline-flex h-12 items-center justify-center rounded-full bg-brand-600 px-8 font-medium text-white shadow-lg shadow-brand-500/20 transition-transform hover:scale-105 hover:bg-brand-700">
              Create New Template
            </button>
          </div>
          
          <div className="flex flex-col md:flex-row gap-4 pt-4 border-t border-slate-100 items-center">
            <div className="relative flex-1 w-full">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400" />
              <input
                type="text"
                placeholder="Search templates by name, industry..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-11 pr-4 h-12 rounded-xl border border-slate-200 bg-slate-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-brand-500/50 focus:border-brand-500 transition-colors"
              />
            </div>
            <div className="flex gap-4 w-full md:w-auto overflow-x-auto pb-2 md:pb-0 hide-scrollbar">
              <button
                onClick={() => setShowFavoritesOnly(!showFavoritesOnly)}
                className={`flex-shrink-0 inline-flex h-12 items-center justify-center rounded-xl border px-5 font-medium transition-colors ${showFavoritesOnly ? 'bg-rose-50 border-rose-200 text-rose-700' : 'bg-white border-slate-200 text-slate-700 hover:bg-slate-50'}`}
              >
                <Heart className={`h-4 w-4 mr-2 ${showFavoritesOnly ? 'fill-rose-500 text-rose-500' : ''}`} />
                Favorites
              </button>
              <div className="relative flex-shrink-0">
                <Layout className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none" />
                <select 
                  value={selectedIndustry}
                  onChange={(e) => setSelectedIndustry(e.target.value)}
                  className="h-12 pl-10 pr-10 rounded-xl border border-slate-200 bg-white appearance-none font-medium text-slate-700 focus:outline-none focus:ring-2 focus:ring-brand-500/50"
                >
                  {industries.map(ind => <option key={ind} value={ind}>{ind === 'All' ? 'All Industries' : ind}</option>)}
                </select>
              </div>
              <div className="relative flex-shrink-0">
                <Palette className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none" />
                <select 
                  value={selectedStyle}
                  onChange={(e) => setSelectedStyle(e.target.value)}
                  className="h-12 pl-10 pr-10 rounded-xl border border-slate-200 bg-white appearance-none font-medium text-slate-700 focus:outline-none focus:ring-2 focus:ring-brand-500/50"
                >
                  {styles.map(sty => <option key={sty} value={sty}>{sty === 'All' ? 'All Styles' : sty}</option>)}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
        {templates.length === 0 ? (
          <div className="text-center py-32 bg-white rounded-3xl border border-slate-200 shadow-sm">
            <LayoutTemplate className="mx-auto h-16 w-16 text-slate-300 mb-4" />
            <h2 className="text-2xl font-bold text-slate-900 mb-2">No templates found</h2>
            <p className="text-slate-500 mb-8 max-w-md mx-auto">It looks like the template library is empty. Let's create something amazing.</p>
            <button onClick={() => navigate('../wizard')} className="inline-flex h-12 items-center justify-center rounded-full bg-brand-600 px-8 font-medium text-white transition-transform hover:scale-105 shadow-lg shadow-brand-500/20">
              Create First Template
            </button>
          </div>
        ) : filteredTemplates.length === 0 ? (
          <div className="text-center py-32">
            <h2 className="text-2xl font-bold text-slate-900 mb-2">No results found</h2>
            <p className="text-slate-500">Try adjusting your filters or search term.</p>
            <button onClick={() => { setSearchTerm(''); setSelectedIndustry('All'); setSelectedStyle('All'); setShowFavoritesOnly(false); }} className="mt-4 text-brand-600 font-medium hover:underline">
              Clear all filters
            </button>
          </div>
        ) : (
          <div className="grid sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2 gap-10">
            {filteredTemplates.map(template => {
              const isFavorite = favorites.includes(template.id);
              return (
                <div key={template.id} className="group flex flex-col bg-white border border-slate-200 rounded-3xl overflow-hidden hover:shadow-2xl hover:shadow-slate-900/5 transition-all duration-300">
                  <div className="relative">
                    <TemplateThumbnail template={template} />
                    
                    {/* Hover Overlay */}
                    <div className="absolute inset-0 z-20 bg-slate-900/0 group-hover:bg-slate-900/30 transition-colors duration-300 flex items-center justify-center backdrop-blur-[0px] group-hover:backdrop-blur-sm opacity-0 group-hover:opacity-100">
                      <div className="flex gap-4 transform translate-y-4 group-hover:translate-y-0 transition-all duration-300">
                        <button 
                          onClick={() => {
                            setCurrentTemplate(template);
                            navigate('../preview');
                          }}
                          className="bg-white text-slate-900 px-6 py-3 rounded-full font-bold shadow-xl flex items-center gap-2 hover:scale-105 transition-transform"
                        >
                          <Play className="h-4 w-4" fill="currentColor" /> Preview
                        </button>
                        <button 
                          onClick={() => {
                            setCurrentTemplate(template);
                            navigate('../preview'); // They edit in preview mode
                          }}
                          className="bg-brand-600 text-white px-6 py-3 rounded-full font-bold shadow-xl flex items-center gap-2 hover:scale-105 transition-transform hover:bg-brand-700"
                        >
                          Use Template
                        </button>
                      </div>
                    </div>

                    <button 
                      onClick={(e) => { e.stopPropagation(); toggleFavorite(template.id); }}
                      className={`absolute top-4 right-4 z-30 h-10 w-10 rounded-full bg-white/90 backdrop-blur flex items-center justify-center shadow-sm transition-transform hover:scale-110 ${isFavorite ? 'text-red-500' : 'text-slate-400 hover:text-red-500'}`}
                    >
                      <Heart className="h-5 w-5" fill={isFavorite ? 'currentColor' : 'none'} />
                    </button>
                  </div>
                  <div className="p-8">
                    <div className="flex gap-2 mb-4">
                      <span className="px-3 py-1 bg-brand-50 text-brand-700 rounded-lg text-xs font-bold tracking-wide uppercase">{template.industry}</span>
                      <span className="px-3 py-1 bg-slate-100 text-slate-600 rounded-lg text-xs font-bold tracking-wide uppercase">{template.style}</span>
                    </div>
                    <h3 className="text-2xl font-bold text-slate-900 mb-2 group-hover:text-brand-600 transition-colors">{template.name}</h3>
                    <div className="flex items-center gap-2 text-sm text-slate-500">
                      <div className="flex gap-1">
                        <div className="h-4 w-4 rounded-full border border-slate-200" style={{ backgroundColor: template.theme.primary }}></div>
                        <div className="h-4 w-4 rounded-full border border-slate-200" style={{ backgroundColor: template.theme.accent }}></div>
                        <div className="h-4 w-4 rounded-full border border-slate-200" style={{ backgroundColor: template.theme.background }}></div>
                      </div>
                      <span className="mx-2 text-slate-300">•</span>
                      <span>{template.sections.length} sections</span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
