import { useEffect, useState } from 'react';
import { CheckCircle2, Clock3, Loader2, RefreshCw, UserPlus } from 'lucide-react';
import { supabase } from '../../lib/supabase';

type Application={id:string;full_name:string;email:string;phone:string|null;national_id_secure:string|null;county:string|null;town:string|null;referring_connector_id:string|null;status:string;provisioning_status:string;provisioned_user_id:string|null;created_at:string};

export default function ConnectorApplications(){
 const [applications,setApplications]=useState<Application[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const {data,error:e}=await supabase.from('connector_applications').select('id,full_name,email,phone,national_id_secure,county,town,referring_connector_id,status,provisioning_status,provisioned_user_id,created_at').order('created_at',{ascending:false});if(e)throw e;setApplications((data||[]) as Application[])}catch(e:unknown){setError(e instanceof Error?e.message:'Unable to load Connector records.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 return <div className="space-y-8">
  <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-widest text-accent-400">Connector Management</div><h1 className="mt-2 text-3xl font-semibold text-white">Connectors</h1><p className="mt-2 text-sm text-gray-400">View Connector registrations and referral relationships. New registrations do not require Owner approval.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-gray-200"><RefreshCw className={loading?'w-4 h-4 animate-spin':'w-4 h-4'}/>Refresh</button></div>
  <div className="grid grid-cols-2 md:grid-cols-3 gap-3"><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="text-xs uppercase tracking-widest text-gray-500">Total registrations</div><div className="mt-2 text-2xl font-semibold text-white">{applications.length}</div></div><div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/[0.04] p-4"><div className="text-xs uppercase tracking-widest text-emerald-300/70">Active</div><div className="mt-2 text-2xl font-semibold text-white">{applications.filter(a=>a.provisioning_status==='completed').length}</div></div><div className="rounded-2xl border border-accent-500/20 bg-accent-500/[0.04] p-4"><div className="text-xs uppercase tracking-widest text-accent-300/70">With referrals</div><div className="mt-2 text-2xl font-semibold text-white">{applications.filter(a=>a.referring_connector_id).length}</div></div></div>
  {error&&<div className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
  {loading?<div className="min-h-[240px] flex items-center justify-center rounded-2xl border border-white/10 bg-white/[0.03]"><Loader2 className="w-7 h-7 animate-spin text-accent-400"/></div>:applications.length===0?<div className="rounded-2xl border border-white/10 bg-white/[0.03] p-10 text-center"><CheckCircle2 className="w-10 h-10 text-accent-400 mx-auto mb-4"/><h2 className="text-lg font-medium text-white">No Connector registrations</h2><p className="mt-2 text-sm text-gray-500">New self-service registrations will appear here.</p></div>:
  <div className="space-y-4">{applications.map(a=><section key={a.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-accent-500/10 border border-accent-500/20 flex items-center justify-center"><UserPlus className="w-5 h-5 text-accent-400"/></div><div><h2 className="text-lg font-medium text-white">{a.full_name}</h2><p className="text-xs text-gray-500">Registered {new Date(a.created_at).toLocaleString()}</p></div></div><div className="mt-5 grid sm:grid-cols-2 lg:grid-cols-3 gap-3 text-sm text-gray-300"><p><span className="text-gray-600">Email:</span> {a.email}</p><p><span className="text-gray-600">Phone:</span> {a.phone||'—'}</p><p><span className="text-gray-600">National ID:</span> {a.national_id_secure||'—'}</p><p><span className="text-gray-600">County:</span> {a.county||'—'}</p><p><span className="text-gray-600">City/Town:</span> {a.town||'—'}</p><p><span className="text-gray-600">Referring Connector:</span> {a.referring_connector_id||'Direct registration'}</p><p><span className="text-gray-600">Status:</span> {a.provisioning_status==='completed'?'Active':a.provisioning_status}</p><p><span className="text-gray-600">User ID:</span> {a.provisioned_user_id||'—'}</p></div></section>)}</div>}
  <div className="flex items-center gap-2 text-xs text-gray-500"><Clock3 className="w-4 h-4"/>Owner/Admin access only. Passwords, hashes, sessions, recovery tokens, and activation links are never stored or displayed here.</div>
 </div>;
}
