import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Ban, Check, CheckCheck, Download, ImagePlus, Loader2, MessageCirclePlus, MoreVertical, Phone, Search, Send, Trash2, UserPlus, Video, VolumeX, X } from 'lucide-react';
import { useAuth } from '../../lib/auth';
import { supabase } from '../../lib/supabase';
import CallOverlayV2, { ActiveCall } from '../../components/portal/CallOverlayV2';

type Person={user_id:string;full_name:string|null;email:string|null;is_online:boolean;last_seen_at:string|null;avatar_url?:string|null};
type Conversation={conversation_id:string;other_user_id:string;other_full_name:string|null;other_email:string|null;updated_at:string};
type Message={id:string;conversation_id:string;sender_id:string;content:string;read_at:string|null;created_at:string};
type Call={id:string;direct_conversation_id:string|null;caller_id:string;callee_id:string;call_type:'voice'|'video';status:string;duration_seconds:number|null;created_at:string;started_at:string|null;ended_at:string|null};
const name=(p?:Person|null)=>p?.full_name?.trim()||p?.email||'Avelixa User';
const time=(s:string)=>new Date(s).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const dateTime=(s:string)=>new Date(s).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const errorText=(e:any)=>[e?.message,e?.details,e?.code&&`Code: ${e.code}`].filter(Boolean).join(' • ')||String(e||'Something went wrong.');
function Avatar({person,size='h-11 w-11'}:{person?:Person|null;size?:string}){return <div className={`${size} relative flex shrink-0 items-center justify-center overflow-hidden rounded-full border border-white/10 bg-accent-500/10 font-semibold text-accent-300`}>{person?.avatar_url?<img src={person.avatar_url} alt="" className="h-full w-full object-cover"/>:name(person).charAt(0).toUpperCase()}<span className={`absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-ink-950 ${person?.is_online?'bg-emerald-400':'bg-gray-500'}`}/></div>}

export default function MessagesV4(){
 const {user}=useAuth();
 const [conversations,setConversations]=useState<Conversation[]>([]),[contacts,setContacts]=useState<Person[]>([]),[people,setPeople]=useState<Record<string,Person>>({}),[unread,setUnread]=useState<Record<string,number>>({});
 const [selected,setSelected]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[calls,setCalls]=useState<Call[]>([]);
 const [query,setQuery]=useState(''),[chatQuery,setChatQuery]=useState(''),[newOpen,setNewOpen]=useState(false),[newQuery,setNewQuery]=useState(''),[found,setFound]=useState<Person|null>(null),[addOpen,setAddOpen]=useState(false),[contactName,setContactName]=useState(''),[identifier,setIdentifier]=useState('');
 const [text,setText]=useState(''),[menu,setMenu]=useState(false),[muted,setMuted]=useState(false),[blocked,setBlocked]=useState(false),[wallpaper,setWallpaper]=useState<string|null>(null),[loading,setLoading]=useState(true),[loadingChat,setLoadingChat]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[activeCall,setActiveCall]=useState<ActiveCall|null>(null),[incoming,setIncoming]=useState<Call|null>(null);
 const pane=useRef<HTMLDivElement|null>(null); const bottom=useRef<HTMLDivElement|null>(null); const firstLoad=useRef(true);
 const person=selected?people[conversations.find(c=>c.conversation_id===selected)?.other_user_id||'']||null:null;
 const refresh=async()=>{if(!user)return;const [{data:c,error:ce},{data:ct,error:te}]=await Promise.all([supabase.rpc('list_direct_conversations'),supabase.rpc('list_communication_contacts')]);if(ce)throw ce;if(te)throw te;const cs=(c||[]) as Conversation[], ps=(ct||[]) as Person[];setConversations(cs);setContacts(ps);const ids=[...new Set([...cs.map(x=>x.other_user_id),...ps.map(x=>x.user_id)])];if(ids.length){const [{data:p},{data:pr}]=await Promise.all([supabase.from('profiles').select('id,full_name,email,avatar_url').in('id',ids),supabase.from('user_presence').select('user_id,is_online,last_seen_at').in('user_id',ids)]);const pm=new Map((p||[]).map((x:any)=>[x.id,x]));const um=new Map((pr||[]).map((x:any)=>[x.user_id,x]));const map:Record<string,Person>={};ids.forEach(id=>{const a=pm.get(id),u=um.get(id);map[id]={user_id:id,full_name:a?.full_name||null,email:a?.email||null,avatar_url:a?.avatar_url||null,is_online:!!u?.is_online,last_seen_at:u?.last_seen_at||null}});setPeople(map)}const ids2=cs.map(x=>x.conversation_id);if(ids2.length){const {data:u}=await supabase.from('direct_messages').select('conversation_id').in('conversation_id',ids2).neq('sender_id',user.id).is('read_at',null);const counts:Record<string,number>={};(u||[]).forEach((x:any)=>counts[x.conversation_id]=(counts[x.conversation_id]||0)+1);setUnread(counts)}else setUnread({})};
 useEffect(()=>{if(!user)return;let alive=true;const init=async()=>{try{await supabase.rpc('communication_set_presence',{p_online:true});await refresh()}catch(e){if(alive)setError(errorText(e))}finally{if(alive)setLoading(false)}};void init();const presence=window.setInterval(()=>void supabase.rpc('communication_set_presence',{p_online:true}),30000);const offline=()=>void supabase.rpc('communication_set_presence',{p_online:false});window.addEventListener('beforeunload',offline);return()=>{alive=false;window.clearInterval(presence);window.removeEventListener('beforeunload',offline);void offline()};},[user?.id]);
 useEffect(()=>{if(!user)return;const ch=supabase.channel(`avelixa-messages-${user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'direct_messages'},({new:m}:any)=>{if(m.sender_id===user.id)return;if(m.conversation_id===selected){setMessages(v=>v.some(x=>x.id===m.id)?v:[...v,m]);void markRead(m.conversation_id)}else setUnread(v=>({...v,[m.conversation_id]:(v[m.conversation_id]||0)+1}));void refresh()}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'direct_messages'},({new:m}:any)=>setMessages(v=>v.map(x=>x.id===m.id?m:x))).on('postgres_changes',{event:'INSERT',schema:'public',table:'call_sessions'},({new:c}:any)=>{if(c.callee_id===user.id&&c.status==='ringing')setIncoming(c);if(c.direct_conversation_id===selected)setCalls(v=>v.some(x=>x.id===c.id)?v:[...v,c])}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'call_sessions'},({new:c}:any)=>{setCalls(v=>v.map(x=>x.id===c.id?c:x));if(incoming?.id===c.id&&c.status!=='ringing')setIncoming(null)}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'user_presence'},({new:p}:any)=>setPeople(v=>v[p.user_id]?{...v,[p.user_id]:{...v[p.user_id],is_online:!!p.is_online,last_seen_at:p.last_seen_at}}:v).subscribe();return()=>{supabase.removeChannel(ch)}},[user?.id,selected,incoming?.id]);
 const load=async(id:string)=>{if(!user)return;setLoadingChat(true);try{const [{data:m,error:me},{data:c,error:ce},{data:p}]=await Promise.all([supabase.from('direct_messages').select('id,conversation_id,sender_id,content,read_at,created_at').eq('conversation_id',id).order('created_at',{ascending:true}),supabase.from('call_sessions').select('id,direct_conversation_id,caller_id,callee_id,call_type,status,duration_seconds,created_at,started_at,ended_at').eq('direct_conversation_id',id).order('created_at',{ascending:true}),supabase.from('conversation_preferences').select('muted,wallpaper').eq('user_id',user.id).eq('conversation_id',id).maybeSingle()]);if(me||ce)throw me||ce;setMessages((m||[]) as Message[]);setCalls((c||[]) as Call[]);setMuted(!!p?.muted);setWallpaper(p?.wallpaper||localStorage.getItem(`avelixa-wallpaper:${user.id}:${id}`));await markRead(id)}catch(e){setError(errorText(e))}finally{setLoadingChat(false)}};
 const markRead=async(id:string)=>{if(!user)return;const {error:e}=await supabase.from('direct_messages').update({read_at:new Date().toISOString()}).eq('conversation_id',id).neq('sender_id',user.id).is('read_at',null);if(!e)setUnread(v=>({...v,[id]:0}))};
 useEffect(()=>{firstLoad.current=true;if(selected){void load(selected)}else{setMessages([]);setCalls([])}},[selected]);
 useEffect(()=>{if(!newOpen||!newQuery.trim()){setFound(null);return}const t=window.setTimeout(async()=>{const {data,error:e}=await supabase.rpc('find_communication_user',{p_identifier:newQuery.trim()});if(e){setError(errorText(e));return}setFound(((data||[]) as Person[])[0]||null)},300);return()=>window.clearTimeout(t)},[newOpen,newQuery]);
 useEffect(()=>{if(!pane.current)return;if(firstLoad.current){firstLoad.current=false;requestAnimationFrame(()=>{if(pane.current)pane.current.scrollTop=pane.current.scrollHeight});return}const near=pane.current.scrollHeight-pane.current.scrollTop-pane.current.clientHeight<220;if(near)requestAnimationFrame(()=>bottom.current?.scrollIntoView({behavior:'smooth'}))},[messages.length,calls.length]);
 const startConversation=async(p:Person)=>{if(!user)return;setBusy(true);try{const {data,error:e}=await supabase.rpc('get_or_create_direct_conversation',{p_recipient_id:p.user_id});if(e)throw e;await supabase.rpc('communication_add_contact',{p_contact_user_id:p.user_id,p_contact_name:p.full_name||p.email});await refresh();setSelected(data as string);setNewOpen(false);setNewQuery('')}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 const addContact=async()=>{if(!contactName.trim()||!identifier.trim()){setError('Enter a name and email address.');return}setBusy(true);try{const {data,error:e}=await supabase.rpc('find_communication_user',{p_identifier:identifier.trim()});if(e)throw e;const p=((data||[]) as Person[])[0];if(!p){setNotice(`${contactName.trim()} is not registered on Avelixa. You can invite them using their email address.`);return}await supabase.rpc('communication_add_contact',{p_contact_user_id:p.user_id,p_contact_name:contactName.trim()});await refresh();setNotice('Contact saved.');setAddOpen(false);setContactName('');setIdentifier('')}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 const send=async(e:FormEvent)=>{e.preventDefault();if(!user||!selected||!text.trim()||blocked)return;setBusy(true);try{const {data,error:e}=await supabase.from('direct_messages').insert({conversation_id:selected,sender_id:user.id,content:text.trim()}).select('id,conversation_id,sender_id,content,read_at,created_at').single();if(e)throw e;setMessages(v=>v.some(x=>x.id===data.id)?v:[...v,data as Message]);setText('');requestAnimationFrame(()=>bottom.current?.scrollIntoView({behavior:'smooth'}))}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 const toggleBlock=async()=>{if(!user||!person)return;setBusy(true);try{const {data}=await supabase.from('user_blocks').select('id').eq('blocker_id',user.id).eq('blocked_id',person.user_id).limit(1);if(data?.length)await supabase.rpc('communication_unblock_user',{p_blocked_id:person.user_id});else await supabase.rpc('communication_block_user',{p_blocked_id:person.user_id});setBlocked(!data?.length);setNotice(data?.length?'Unblocked.':'Blocked.')}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 const toggleMute=async()=>{if(!user||!selected)return;const next=!muted;const {error:e}=await supabase.from('conversation_preferences').upsert({user_id:user.id,conversation_id:selected,muted:next},{onConflict:'user_id,conversation_id'});if(e)setError(errorText(e));else setMuted(next)};
 const setBg=(url:string|null)=>{if(!user||!selected)return;setWallpaper(url);if(url)localStorage.setItem(`avelixa-wallpaper:${user.id}:${selected}`,url);else localStorage.removeItem(`avelixa-wallpaper:${user.id}:${selected}`);void supabase.from('conversation_preferences').upsert({user_id:user.id,conversation_id:selected,wallpaper:url},{onConflict:'user_id,conversation_id'})};
 const exportChat=()=>{const lines=timeline.map(i=>i.kind==='message'?`[${dateTime(i.at)}] ${i.message?.sender_id===user?.id?'You':name(person)}: ${i.message?.content}`:`[${dateTime(i.at)}] ${i.call?.call_type==='video'?'Video':'Voice'} call — ${i.call?.status}`);const blob=new Blob([lines.join('\n')],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`avelixa-chat-${name(person)}.txt`;a.click();URL.revokeObjectURL(a.href)};
 const timeline=useMemo(()=>[...messages.map(m=>({kind:'message' as const,at:m.created_at,message:m})),...calls.map(c=>({kind:'call' as const,at:c.created_at,call:c}))].sort((a,b)=>+new Date(a.at)-+new Date(b.at)).filter(i=>!chatQuery||i.kind==='message'&&i.message!.content.toLowerCase().includes(chatQuery.toLowerCase())),[messages,calls,chatQuery]);
 const chats=useMemo(()=>conversations.filter(c=>{const p=people[c.other_user_id];const q=query.toLowerCase();return !q||name(p).toLowerCase().includes(q)||(p?.email||'').toLowerCase().includes(q)}),[conversations,people,query]);
 if(!user)return null;if(loading)return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-accent-400"/></div>;
 return <div className="h-[calc(100vh-9rem)] min-h-[600px] overflow-hidden rounded-3xl border border-white/10 bg-ink-950 shadow-2xl">{error&&<div className="absolute z-50 m-4 max-w-xl rounded-xl border border-red-500/30 bg-red-950/90 px-4 py-3 text-sm text-red-200">{error}<button className="ml-3" onClick={()=>setError(null)}><X className="inline h-4 w-4"/></button></div>}{notice&&<div className="absolute z-50 m-4 rounded-xl border border-accent-500/20 bg-ink-900 px-4 py-3 text-sm text-white">{notice}<button className="ml-3" onClick={()=>setNotice(null)}><X className="inline h-4 w-4"/></button></div>}<div className="grid h-full md:grid-cols-[330px_1fr]"> <aside className={`${selected?'hidden md:flex':'flex'} flex-col border-r border-white/10`}><div className="flex items-center justify-between px-5 py-4"><div><h1 className="text-lg font-semibold text-white">Messages</h1><p className="text-xs text-gray-500">Your contacts and conversations</p></div><button onClick={()=>setAddOpen(true)} className="rounded-full bg-accent-500 p-2 text-white" title="Add contact"><UserPlus className="h-5 w-5"/></button></div><div className="px-4 pb-3"><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3"><Search className="h-4 w-4 text-gray-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your chats" className="w-full bg-transparent py-2.5 text-sm text-white outline-none"/></div></div><div className="flex-1 overflow-y-auto">{chats.length===0?<div className="px-6 py-12 text-center text-sm text-gray-500">No conversations yet.<button onClick={()=>setNewOpen(true)} className="mt-3 block w-full text-accent-300">Start a new chat</button></div>:chats.map(c=>{const p=people[c.other_user_id];return <button key={c.conversation_id} onClick={()=>setSelected(c.conversation_id)} className="flex w-full items-center gap-3 border-b border-white/5 px-4 py-3 text-left hover:bg-white/5"><Avatar person={p}/><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><span className="truncate font-medium text-white">{name(p)}</span>{unread[c.conversation_id]?<span className="min-w-5 rounded-full bg-red-500 px-1.5 text-center text-[11px] font-bold text-white">{unread[c.conversation_id]}</span>:null}</div><div className="flex items-center gap-2 text-xs"><span className={p?.is_online?'text-emerald-400':'text-gray-500'}>{p?.is_online?'Online':'Offline'}</span><span className="truncate text-gray-500">{p?.email}</span></div></div></button>})}</div><button onClick={()=>setNewOpen(true)} className="m-4 flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/5 py-3 text-sm font-medium text-white hover:bg-white/10"><MessageCirclePlus className="h-4 w-4"/>New chat</button></aside>
 <main className={`${selected?'flex':'hidden md:flex'} min-w-0 flex-col`}>{!selected?<div className="flex flex-1 items-center justify-center text-center"><div><MessageCirclePlus className="mx-auto h-12 w-12 text-gray-700"/><p className="mt-4 text-gray-400">Select a conversation to start messaging.</p></div></div>:<><header className="flex items-center gap-3 border-b border-white/10 px-4 py-3"><button onClick={()=>setSelected(null)} className="md:hidden"><ArrowLeft className="h-5 w-5 text-gray-300"/></button><Avatar person={person}/><div className="min-w-0 flex-1"><div className="font-semibold text-white">{name(person)}</div><div className={`text-xs ${person?.is_online?'text-emerald-400':'text-gray-500'}`}>{person?.is_online?'Online':person?.last_seen_at?`Last seen ${dateTime(person.last_seen_at)}`:'Offline'}</div></div><button onClick={()=>void (person&&setActiveCall({id:'',callType:'voice',callerId:user.id,calleeId:person.user_id,remoteName:name(person),isIncoming:false,directConversationId:selected}))}><Phone className="h-5 w-5 text-gray-300"/></button><button onClick={()=>void (person&&setActiveCall({id:'',callType:'video',callerId:user.id,calleeId:person.user_id,remoteName:name(person),isIncoming:false,directConversationId:selected}))}><Video className="h-5 w-5 text-gray-300"/></button><button onClick={()=>setMenu(v=>!v)}><MoreVertical className="h-5 w-5 text-gray-300"/></button></header>{menu&&<div className="absolute right-5 z-30 mt-2 w-56 rounded-xl border border-white/10 bg-ink-900 p-2 shadow-2xl"><button onClick={()=>{setChatQuery('');setMenu(false)}} className="w-full rounded-lg px-3 py-2 text-left text-sm text-white hover:bg-white/5">Search conversation</button><button onClick={exportChat} className="w-full rounded-lg px-3 py-2 text-left text-sm text-white hover:bg-white/5">Export chat</button><button onClick={toggleMute} className="w-full rounded-lg px-3 py-2 text-left text-sm text-white hover:bg-white/5">{muted?'Unmute chat':'Mute chat'}</button><button onClick={toggleBlock} className="w-full rounded-lg px-3 py-2 text-left text-sm text-red-300 hover:bg-white/5">{blocked?'Unblock':'Block'} contact</button><label className="flex cursor-pointer items-center gap-2 rounded-lg px-3 py-2 text-sm text-white hover:bg-white/5"><ImagePlus className="h-4 w-4"/>Change wallpaper<input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>setBg(String(r.result));r.readAsDataURL(f)}}}/></label><button onClick={()=>setBg(null)} className="w-full rounded-lg px-3 py-2 text-left text-sm text-gray-400 hover:bg-white/5">Remove wallpaper</button></div>}
 {chatQuery&&<div className="border-b border-white/10 px-4 py-2"><input autoFocus value={chatQuery} onChange={e=>setChatQuery(e.target.value)} placeholder="Search this conversation" className="w-full rounded-lg bg-white/5 px-3 py-2 text-sm text-white outline-none"/></div>}
 <div ref={pane} className="flex-1 overflow-y-auto px-4 py-5" style={wallpaper?{backgroundImage:`linear-gradient(rgba(7,10,20,.78),rgba(7,10,20,.78)),url(${wallpaper})`,backgroundSize:'cover',backgroundAttachment:'local'}:undefined}>{loadingChat?<div className="flex h-full items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-accent-400"/></div>:timeline.length===0?<div className="flex h-full items-center justify-center text-sm text-gray-500">No messages yet.</div>:<div className="mx-auto flex max-w-3xl flex-col gap-2">{timeline.map(i=>i.kind==='message'?<div key={`m-${i.message!.id}`} className={`flex ${i.message!.sender_id===user.id?'justify-end':'justify-start'}`}><div className={`max-w-[78%] rounded-2xl px-4 py-2.5 ${i.message!.sender_id===user.id?'bg-accent-500 text-white':'bg-white/10 text-gray-100'}`}><div className="whitespace-pre-wrap break-words text-sm">{i.message!.content}</div><div className="mt-1 flex items-center justify-end gap-1 text-[10px] opacity-70"><span>{time(i.at)}</span>{i.message!.sender_id===user.id&&(i.message!.read_at?<CheckCheck className="h-3.5 w-3.5 text-sky-300"/>:<Check className="h-3.5 w-3.5"/>)}</div></div></div>:<div key={`c-${i.call!.id}`} className={`flex ${i.call!.caller_id===user.id?'justify-end':'justify-start'}`}><div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-2 text-xs text-gray-400"><div className="flex items-center gap-2">{i.call!.call_type==='video'?<Video className="h-4 w-4"/>:<Phone className="h-4 w-4"/>}<span>{i.call!.caller_id===user.id?'You':'Incoming'} {i.call!.call_type} call • {i.call!.status}</span></div><div className="mt-1 text-right text-[10px]">{dateTime(i.at)}{i.call!.duration_seconds!=null?` • ${i.call!.duration_seconds}s`:''}</div></div></div>)}<div ref={bottom}/></div>}</div><form onSubmit={send} className="border-t border-white/10 p-3"><div className="mx-auto flex max-w-3xl items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-3 py-2"><input value={text} onChange={e=>setText(e.target.value)} disabled={blocked} placeholder={blocked?'You blocked this contact':'Type a message…'} className="flex-1 bg-transparent text-sm text-white outline-none"/><button disabled={busy||!text.trim()||blocked} className="rounded-xl bg-accent-500 p-2 text-white disabled:opacity-40"><Send className="h-4 w-4"/></button></div></form></>}</main></div>
 {newOpen&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-ink-900 p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-white">New chat</h2><button onClick={()=>setNewOpen(false)}><X className="h-5 w-5 text-gray-400"/></button></div><p className="mt-2 text-xs text-gray-500">Search for one person by name, email, phone or Connector ID. No Avelixa directory is shown.</p><input autoFocus value={newQuery} onChange={e=>setNewQuery(e.target.value)} placeholder="Enter name, email or Connector ID" className="mt-4 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm text-white outline-none"/>{found?<button disabled={busy} onClick={()=>void startConversation(found)} className="mt-3 flex w-full items-center gap-3 rounded-xl bg-white/5 p-3 text-left hover:bg-white/10"><Avatar person={found}/><div><div className="font-medium text-white">{name(found)}</div><div className="text-xs text-gray-500">{found.is_online?'Online':'Offline'}</div></div></button>:newQuery.trim()?<div className="mt-4 text-sm text-gray-500">No matching Avelixa user.</div>:null}<button onClick={()=>{setNewOpen(false);setAddOpen(true)}} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 py-3 text-sm text-white"><UserPlus className="h-4 w-4"/>Add contact manually</button></div></div>}
 {addOpen&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-ink-900 p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-white">Add contact</h2><button onClick={()=>setAddOpen(false)}><X className="h-5 w-5 text-gray-400"/></button></div><input value={contactName} onChange={e=>setContactName(e.target.value)} placeholder="Contact name" className="mt-4 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm text-white outline-none"/><input value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="Email address" className="mt-3 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm text-white outline-none"/><button disabled={busy} onClick={()=>void addContact()} className="mt-4 w-full rounded-xl bg-accent-500 py-3 text-sm font-semibold text-white">{busy?'Saving…':'Save contact'}</button></div></div>}
 {incoming&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 p-4"><div className="w-full max-w-sm rounded-3xl border border-white/10 bg-ink-900 p-6 text-center"><Avatar person={people[incoming.caller_id]} size="h-20 w-20 mx-auto"/><h2 className="mt-4 text-xl font-semibold text-white">{name(people[incoming.caller_id])}</h2><p className="mt-1 text-sm text-gray-400">Incoming {incoming.call_type} call</p><div className="mt-7 flex justify-center gap-4"><button onClick={async()=>{await supabase.from('call_sessions').update({status:'declined',ended_at:new Date().toISOString()}).eq('id',incoming.id);setIncoming(null)}} className="rounded-full bg-red-500/15 p-4 text-red-300"><Ban className="h-6 w-6"/></button><button onClick={()=>{setActiveCall({id:incoming.id,callType:incoming.call_type,callerId:incoming.caller_id,calleeId:incoming.callee_id,remoteName:name(people[incoming.caller_id]),isIncoming:true,directConversationId:incoming.direct_conversation_id});setIncoming(null)}} className="rounded-full bg-emerald-500 p-4 text-white"><Phone className="h-6 w-6"/></button></div></div></div>}
 {activeCall&&<CallOverlayV2 call={activeCall} onClose={()=>setActiveCall(null)}/>}</div>;
}
