import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Ban, Check, CheckCheck, Download, ImagePlus, Loader2, MoreVertical, Phone, PhoneOff, Search, Send, Trash2, UserPlus, Video, VolumeX, X } from 'lucide-react';
import { useAuth } from '../../lib/auth';
import { supabase } from '../../lib/supabase';
import CallOverlayV2, { ActiveCall } from '../../components/portal/CallOverlayV2';

type Person={user_id:string;full_name:string|null;email:string|null;is_online:boolean;last_seen_at:string|null;avatar_url?:string|null};
type Conversation={conversation_id:string;other_user_id:string;other_full_name:string|null;other_email:string|null;updated_at:string};
type Message={id:string;conversation_id:string;sender_id:string;content:string;read_at:string|null;created_at:string};
type Call={id:string;direct_conversation_id:string|null;caller_id:string;callee_id:string;call_type:'voice'|'video';status:string;duration_seconds:number|null;created_at:string;started_at:string|null;ended_at:string|null};
type TimelineItem={kind:'message'|'call';at:string;message?:Message;call?:Call};
const displayName=(p?:Person|null)=>p?.full_name?.trim()||p?.email||'Avelixa User';
const time=(v:string)=>new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const dateTime=(v:string)=>new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const messageError=(e:any)=>[e?.message,e?.details,e?.hint,e?.code&&`Code: ${e.code}`].filter(Boolean).join(' • ')||'Something went wrong.';

function Avatar({person,size='h-11 w-11'}:{person?:Person|null;size?:string}){return <div className={`${size} relative flex shrink-0 items-center justify-center overflow-hidden rounded-full border border-white/10 bg-accent-500/10 font-semibold text-accent-300`}>{person?.avatar_url?<img src={person.avatar_url} alt="" className="h-full w-full object-cover"/>:displayName(person).charAt(0).toUpperCase()}<span className={`absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-ink-950 ${person?.is_online?'bg-emerald-400':'bg-gray-500'}`}/></div>}

export default function MessagesV5(){
 const {user}=useAuth();
 const [conversations,setConversations]=useState<Conversation[]>([]),[people,setPeople]=useState<Record<string,Person>>({}),[unread,setUnread]=useState<Record<string,number>>({});
 const [selected,setSelected]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[calls,setCalls]=useState<Call[]>([]);
 const [query,setQuery]=useState(''),[chatQuery,setChatQuery]=useState('');
 const [addOpen,setAddOpen]=useState(false),[contactName,setContactName]=useState(''),[identifier,setIdentifier]=useState(''),[found,setFound]=useState<Person|null>(null),[lookupBusy,setLookupBusy]=useState(false);
 const [text,setText]=useState(''),[menu,setMenu]=useState(false),[muted,setMuted]=useState(false),[blocked,setBlocked]=useState(false),[wallpaper,setWallpaper]=useState<string|null>(null),[loading,setLoading]=useState(true),[loadingChat,setLoadingChat]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[activeCall,setActiveCall]=useState<ActiveCall|null>(null),[incoming,setIncoming]=useState<Call|null>(null);
 const pane=useRef<HTMLDivElement|null>(null),bottom=useRef<HTMLDivElement|null>(null),initialScroll=useRef(true),userNearBottom=useRef(true);
 const conversation=selected?conversations.find(c=>c.conversation_id===selected)||null:null;
 const person=conversation?people[conversation.other_user_id]||null:null;

 const refreshDirectory=useCallback(async()=>{if(!user)return;const [{data:c,error:ce},{data:ct,error:te}]=await Promise.all([supabase.rpc('list_direct_conversations'),supabase.rpc('list_communication_contacts')]);if(ce)throw ce;if(te)throw te;const cs=(c||[]) as Conversation[],contacts=(ct||[]) as Person[];setConversations(cs);const ids=[...new Set(cs.map(x=>x.other_user_id).concat(contacts.map(x=>x.user_id)))];if(!ids.length){setPeople({});setUnread({});return}const [{data:profiles},{data:presence},{data:unreadRows}]=await Promise.all([supabase.from('profiles').select('id,full_name,email,avatar_url').in('id',ids),supabase.from('user_presence').select('user_id,is_online,last_seen_at').in('user_id',ids),supabase.from('direct_messages').select('conversation_id').in('conversation_id',cs.map(x=>x.conversation_id)).neq('sender_id',user.id).is('read_at',null)]);const pm=new Map((profiles||[]).map((p:any)=>[p.id,p])),um=new Map((presence||[]).map((p:any)=>[p.user_id,p]));const map:Record<string,Person>={};ids.forEach(id=>{const p=pm.get(id),pr=um.get(id);map[id]={user_id:id,full_name:p?.full_name||null,email:p?.email||null,avatar_url:p?.avatar_url||null,is_online:!!pr?.is_online,last_seen_at:pr?.last_seen_at||null}});setPeople(map);const counts:Record<string,number>={};(unreadRows||[]).forEach((r:any)=>counts[r.conversation_id]=(counts[r.conversation_id]||0)+1);setUnread(counts)},[user?.id]);

 const markRead=useCallback(async(id:string)=>{if(!user)return;const {error:e}=await supabase.from('direct_messages').update({read_at:new Date().toISOString()}).eq('conversation_id',id).neq('sender_id',user.id).is('read_at',null);if(!e)setUnread(v=>({...v,[id]:0}))},[user?.id]);

 useEffect(()=>{if(!user)return;let alive=true;const init=async()=>{try{await supabase.rpc('communication_set_presence',{p_online:true});await refreshDirectory()}catch(e){if(alive)setError(messageError(e))}finally{if(alive)setLoading(false)}};void init();const heartbeat=window.setInterval(()=>{void supabase.rpc('communication_set_presence',{p_online:true})},25000);const presenceRefresh=window.setInterval(async()=>{if(!alive)return;const ids=Object.keys(people);if(!ids.length)return;const {data}=await supabase.from('user_presence').select('user_id,is_online,last_seen_at').in('user_id',ids);if(data)setPeople(v=>{const next={...v};(data as any[]).forEach(p=>{if(next[p.user_id])next[p.user_id]={...next[p.user_id],is_online:!!p.is_online,last_seen_at:p.last_seen_at||null}});return next})},10000);const off=()=>{void supabase.rpc('communication_set_presence',{p_online:false})};window.addEventListener('beforeunload',off);return()=>{alive=false;window.clearInterval(heartbeat);window.clearInterval(presenceRefresh);window.removeEventListener('beforeunload',off);off()}},[user?.id]);

 useEffect(()=>{if(!user)return;const channel=supabase.channel(`avelixa-message-events-${user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'direct_messages'},({new:m}:any)=>{if(m.sender_id===user.id)return;if(m.conversation_id===selected){setMessages(v=>v.some(x=>x.id===m.id)?v:[...v,m]);void markRead(m.conversation_id)}else setUnread(v=>({...v,[m.conversation_id]:(v[m.conversation_id]||0)+1}));void refreshDirectory()}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'direct_messages'},({new:m}:any)=>{if(m.conversation_id===selected)setMessages(v=>v.map(x=>x.id===m.id?m:x))}).on('postgres_changes',{event:'INSERT',schema:'public',table:'call_sessions'},({new:c}:any)=>{if(c.callee_id===user.id&&c.status==='ringing')setIncoming(c as Call);if(c.direct_conversation_id===selected)setCalls(v=>v.some(x=>x.id===c.id)?v:[...v,c as Call])}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'call_sessions'},({new:c}:any)=>{if(c.direct_conversation_id===selected)setCalls(v=>v.map(x=>x.id===c.id?c:x));if(incoming?.id===c.id&&c.status!=='ringing')setIncoming(null)}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'user_presence'},({new:p}:any)=>setPeople(v=>v[p.user_id]?{...v,[p.user_id]:{...v[p.user_id],is_online:!!p.is_online,last_seen_at:p.last_seen_at||null}}:v).subscribe();return()=>{void supabase.removeChannel(channel)}},[user?.id,selected,incoming?.id,markRead]);

 useEffect(()=>{if(!selected||!user)return;let alive=true;setLoadingChat(true);initialScroll.current=true;(async()=>{try{const [{data:m,error:me},{data:c,error:ce},{data:p},{data:b}]=await Promise.all([supabase.from('direct_messages').select('id,conversation_id,sender_id,content,read_at,created_at').eq('conversation_id',selected).order('created_at',{ascending:true}),supabase.from('call_sessions').select('id,direct_conversation_id,caller_id,callee_id,call_type,status,duration_seconds,created_at,started_at,ended_at').eq('direct_conversation_id',selected).order('created_at',{ascending:true}),supabase.from('conversation_preferences').select('muted,wallpaper').eq('user_id',user.id).eq('conversation_id',selected).maybeSingle(),supabase.from('user_blocks').select('id').eq('blocker_id',user.id).eq('blocked_id',conversation?.other_user_id||'').limit(1)]);if(me||ce)throw me||ce;if(!alive)return;setMessages((m||[]) as Message[]);setCalls((c||[]) as Call[]);setMuted(!!p?.muted);setWallpaper(p?.wallpaper||localStorage.getItem(`avelixa-wallpaper:${user.id}:${selected}`));setBlocked(!!b?.length);await markRead(selected)}catch(e){if(alive)setError(messageError(e))}finally{if(alive)setLoadingChat(false)}})();return()=>{alive=false}},[selected,user?.id,conversation?.other_user_id,markRead]);

 useEffect(()=>{if(!addOpen||!identifier.trim()){setFound(null);return}const timer=window.setTimeout(async()=>{setLookupBusy(true);try{const {data,error:e}=await supabase.rpc('find_communication_user',{p_identifier:identifier.trim()});if(e)throw e;setFound(((data||[]) as Person[])[0]||null)}catch(e){setError(messageError(e))}finally{setLookupBusy(false)}},350);return()=>window.clearTimeout(timer)},[addOpen,identifier]);

 const timeline=useMemo<TimelineItem[]>(()=>[...messages.map(message=>({kind:'message' as const,at:message.created_at,message})),...calls.map(call=>({kind:'call' as const,at:call.created_at,call}))].sort((a,b)=>+new Date(a.at)-+new Date(b.at)).filter(item=>!chatQuery||item.kind==='message'&&item.message!.content.toLowerCase().includes(chatQuery.toLowerCase())),[messages,calls,chatQuery]);
 const chats=useMemo(()=>conversations.filter(c=>{const p=people[c.other_user_id];const q=query.trim().toLowerCase();return !q||displayName(p).toLowerCase().includes(q)||(p?.email||'').toLowerCase().includes(q)}),[conversations,people,query]);

 useEffect(()=>{const el=pane.current;if(!el)return;const onScroll=()=>{userNearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<180};el.addEventListener('scroll',onScroll,{passive:true});if(initialScroll.current&&timeline.length){requestAnimationFrame(()=>{el.scrollTop=el.scrollHeight;initialScroll.current=false;userNearBottom.current=true})}return()=>el.removeEventListener('scroll',onScroll)},[selected,timeline.length]);
 useEffect(()=>{if(!pane.current||initialScroll.current)return;if(userNearBottom.current)requestAnimationFrame(()=>{if(pane.current)pane.current.scrollTop=pane.current.scrollHeight})},[timeline.length]);

 const send=async(e:FormEvent)=>{e.preventDefault();if(!user||!selected||!text.trim()||blocked)return;setBusy(true);try{const {data,error:e}=await supabase.from('direct_messages').insert({conversation_id:selected,sender_id:user.id,content:text.trim()}).select('id,conversation_id,sender_id,content,read_at,created_at').single();if(e)throw e;setMessages(v=>v.some(x=>x.id===data.id)?v:[...v,data as Message]);setText('');requestAnimationFrame(()=>{if(pane.current)pane.current.scrollTop=pane.current.scrollHeight});void refreshDirectory()}catch(e){setError(messageError(e))}finally{setBusy(false)}};
 const addContact=async()=>{if(!contactName.trim()||!identifier.trim()){setError('Enter the contact name and email address.');return}setBusy(true);try{if(!found){setNotice(`${contactName.trim()} is not on Avelixa yet. We can invite them using ${identifier.trim()}.`);return}await supabase.rpc('communication_add_contact',{p_contact_user_id:found.user_id,p_contact_name:contactName.trim()});await refreshDirectory();setAddOpen(false);setContactName('');setIdentifier('');setFound(null);setNotice('Contact saved.')}catch(e){setError(messageError(e))}finally{setBusy(false)}};
 const openChat=async(p:Person)=>{if(!user)return;setBusy(true);try{const {data,error:e}=await supabase.rpc('get_or_create_direct_conversation',{p_recipient_id:p.user_id});if(e)throw e;await supabase.rpc('communication_add_contact',{p_contact_user_id:p.user_id,p_contact_name:p.full_name||p.email});await refreshDirectory();setSelected(data as string)}catch(e){setError(messageError(e))}finally{setBusy(false)}};
 const toggleBlock=async()=>{if(!user||!person)return;setBusy(true);try{if(blocked){await supabase.rpc('communication_unblock_user',{p_blocked_id:person.user_id})}else{await supabase.rpc('communication_block_user',{p_blocked_id:person.user_id})}setBlocked(!blocked)}catch(e){setError(messageError(e))}finally{setBusy(false)}};
 const toggleMute=async()=>{if(!user||!selected)return;const next=!muted;const {error:e}=await supabase.from('conversation_preferences').upsert({user_id:user.id,conversation_id:selected,muted:next},{onConflict:'user_id,conversation_id'});if(e)setError(messageError(e));else setMuted(next)};
 const clearChat=async()=>{if(!selected)return;const now=new Date().toISOString();const {error:e}=await supabase.from('conversation_preferences').upsert({user_id:user.id,conversation_id:selected,cleared_at:now},{onConflict:'user_id,conversation_id'});if(e)setError(messageError(e));else{setMessages([]);setCalls([])}};
 const setWallpaperValue=(url:string|null)=>{if(!selected||!user)return;setWallpaper(url);const key=`avelixa-wallpaper:${user.id}:${selected}`;if(url)localStorage.setItem(key,url);else localStorage.removeItem(key);void supabase.from('conversation_preferences').upsert({user_id:user.id,conversation_id:selected,wallpaper:url},{onConflict:'user_id,conversation_id'})};
 const wallpaperUpload=(file:File)=>{const reader=new FileReader();reader.onload=()=>setWallpaperValue(String(reader.result));reader.readAsDataURL(file)};
 const exportChat=()=>{const lines=timeline.map(item=>item.kind==='message'?`[${dateTime(item.at)}] ${item.message?.sender_id===user?.id?'You':displayName(person)}: ${item.message?.content}`:`[${dateTime(item.at)}] ${item.call?.call_type==='video'?'Video':'Voice'} call — ${item.call?.status}`);const blob=new Blob([lines.join('\n')],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`avelixa-chat-${displayName(person)}.txt`;a.click();URL.revokeObjectURL(url)};
 const startCall=async(callType:'voice'|'video')=>{if(!user||!conversation||blocked||busy)return;setBusy(true);try{const {data:allowed,error:e}=await supabase.rpc('communication_can_contact',{p_other_user_id:conversation.other_user_id});if(e)throw e;if(!allowed)throw new Error('This user is unavailable for communication.');const {data,error:ce}=await supabase.from('call_sessions').insert({direct_conversation_id:selected,caller_id:user.id,callee_id:conversation.other_user_id,call_type:callType,status:'ringing'}).select('id,direct_conversation_id,caller_id,callee_id,call_type,status,duration_seconds,created_at,started_at,ended_at').single();if(ce)throw ce;setCalls(v=>v.some(x=>x.id===data.id)?v:[...v,data as Call]);setActiveCall({id:data.id,callType,callerId:user.id,calleeId:conversation.other_user_id,remoteName:displayName(person),isIncoming:false,directConversationId:selected})}catch(e){setError(`Could not start call: ${messageError(e)}`)}finally{setBusy(false)}};
 const incomingPerson=incoming?people[incoming.caller_id]||null:null;
 if(!user)return null;
 if(loading)return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-accent-400"/></div>;
 return <div className="relative h-[calc(100vh-9rem)] min-h-[600px] overflow-hidden rounded-3xl border border-white/10 bg-ink-950 shadow-2xl">
  {error&&<div className="absolute left-4 right-4 top-4 z-[90] rounded-xl border border-red-500/30 bg-red-950/95 px-4 py-3 text-sm text-red-200">{error}<button className="float-right" onClick={()=>setError(null)}><X className="h-4 w-4"/></button></div>}
  {notice&&<div className="absolute left-4 right-4 top-4 z-[90] rounded-xl border border-accent-500/20 bg-ink-900/95 px-4 py-3 text-sm text-white">{notice}<button className="float-right" onClick={()=>setNotice(null)}><X className="h-4 w-4"/></button></div>}
  <div className="grid h-full md:grid-cols-[340px_1fr]">
   <aside className={`${selected?'hidden md:flex':'flex'} flex-col border-r border-white/10`}>
    <div className="flex items-center justify-between px-5 py-4"><div><h1 className="text-lg font-semibold text-white">Messages</h1><p className="text-xs text-gray-500">Your contacts and conversations</p></div><button onClick={()=>setAddOpen(true)} title="Add contact" className="rounded-full bg-accent-500 p-2 text-white"><UserPlus className="h-5 w-5"/></button></div>
    <div className="px-4 pb-3"><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3"><Search className="h-4 w-4 text-gray-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your chats" className="w-full bg-transparent py-2.5 text-sm text-white outline-none"/></div></div>
    <div className="flex-1 overflow-y-auto">{chats.length===0?<div className="px-6 py-12 text-center text-sm text-gray-500">No saved conversations yet.<button onClick={()=>setAddOpen(true)} className="mt-3 text-accent-300">Add a contact</button></div>:chats.map(c=>{const p=people[c.other_user_id];const count=unread[c.conversation_id]||0;return <button key={c.conversation_id} onClick={()=>setSelected(c.conversation_id)} className={`flex w-full items-center gap-3 border-b border-white/5 px-4 py-3 text-left hover:bg-white/5 ${selected===c.conversation_id?'bg-white/5':''}`}><Avatar person={p}/><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="truncate text-sm font-semibold text-white">{displayName(p)}</span>{p?.is_online&&<span className="h-2.5 w-2.5 shrink-0 rounded-full bg-emerald-400"/>}</span><span className="block truncate text-xs text-gray-500">{p?.is_online?'Online':p?.last_seen_at?`Last seen ${time(p.last_seen_at)}`:'Offline'}</span></span>{count>0&&<span className="flex h-6 min-w-6 items-center justify-center rounded-full bg-red-500 px-1.5 text-xs font-bold text-white">{count}</span>}</button>})}</div>
   </aside>
   <main className={`${selected?'flex':'hidden md:flex'} min-w-0 flex-col`}>
    {!conversation?<div className="flex flex-1 items-center justify-center text-center"><div><MessageCircleIcon/><h2 className="mt-4 text-lg font-semibold text-white">Select a conversation</h2><p className="mt-1 text-sm text-gray-500">Choose one of your saved contacts or add a new one.</p></div></div>:<>
     <header className="flex items-center gap-3 border-b border-white/10 px-4 py-3"><button className="md:hidden" onClick={()=>setSelected(null)}><ArrowLeft className="h-5 w-5 text-gray-300"/></button><Avatar person={person}/><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold text-white">{displayName(person)}</div><div className="text-xs"><span className={person?.is_online?'text-emerald-400':'text-gray-500'}>{person?.is_online?'Online':person?.last_seen_at?`Last seen ${time(person.last_seen_at)}`:'Offline'}</span></div></div><button title="Voice call" disabled={busy||blocked} onClick={()=>void startCall('voice')} className="rounded-full p-2 text-gray-300 hover:bg-white/5 disabled:opacity-40"><Phone className="h-5 w-5"/></button><button title="Video call" disabled={busy||blocked} onClick={()=>void startCall('video')} className="rounded-full p-2 text-gray-300 hover:bg-white/5 disabled:opacity-40"><Video className="h-5 w-5"/></button><button onClick={()=>setMenu(v=>!v)} className="rounded-full p-2 text-gray-300 hover:bg-white/5"><MoreVertical className="h-5 w-5"/></button></header>
     {menu&&<div className="absolute right-4 top-16 z-40 w-56 rounded-2xl border border-white/10 bg-ink-900 p-2 shadow-2xl"><button onClick={()=>{setChatQuery('');setMenu(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2 text-sm text-gray-200 hover:bg-white/5"><Search className="h-4 w-4"/>Search conversation</button><button onClick={()=>{exportChat();setMenu(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2 text-sm text-gray-200 hover:bg-white/5"><Download className="h-4 w-4"/>Export chat</button><button onClick={()=>{void clearChat();setMenu(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2 text-sm text-gray-200 hover:bg-white/5"><Trash2 className="h-4 w-4"/>Clear chat</button><button onClick={()=>{void toggleMute();setMenu(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2 text-sm text-gray-200 hover:bg-white/5"><VolumeX className="h-4 w-4"/>{muted?'Unmute chat':'Mute chat'}</button><button onClick={()=>{void toggleBlock();setMenu(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2 text-sm text-gray-200 hover:bg-white/5"><Ban className="h-4 w-4"/>{blocked?'Unblock user':'Block user'}</button><label className="flex cursor-pointer items-center gap-3 rounded-xl px-3 py-2 text-sm text-gray-200 hover:bg-white/5"><ImagePlus className="h-4 w-4"/>Change wallpaper<input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)wallpaperUpload(f)}}/></label>{wallpaper&&<button onClick={()=>{setWallpaperValue(null);setMenu(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2 text-sm text-gray-400 hover:bg-white/5"><X className="h-4 w-4"/>Remove wallpaper</button>}</div>}
     {chatQuery&&<div className="border-b border-white/10 px-4 py-2"><input autoFocus value={chatQuery} onChange={e=>setChatQuery(e.target.value)} placeholder="Search this conversation" className="w-full rounded-lg bg-white/5 px-3 py-2 text-sm text-white outline-none"/></div>}
     <div ref={pane} className="flex-1 overflow-y-auto px-4 py-5" style={wallpaper?{backgroundImage:`linear-gradient(rgba(7,10,20,.82),rgba(7,10,20,.82)),url(${wallpaper})`,backgroundSize:'cover',backgroundPosition:'center'}:undefined}>
      {loadingChat?<div className="flex h-full items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-accent-400"/></div>:timeline.length===0?<div className="flex h-full items-center justify-center text-sm text-gray-500">No messages yet.</div>:<div className="mx-auto flex max-w-3xl flex-col gap-2">{timeline.map(item=>item.kind==='message'?<div key={`m-${item.message!.id}`} className={`flex ${item.message!.sender_id===user.id?'justify-end':'justify-start'}`}><div className={`max-w-[78%] rounded-2xl px-4 py-2.5 ${item.message!.sender_id===user.id?'rounded-br-md bg-accent-500 text-white':'rounded-bl-md bg-white/10 text-gray-100'}`}><div className="whitespace-pre-wrap break-words text-sm">{item.message!.content}</div><div className="mt-1 flex items-center justify-end gap-1 text-[10px] opacity-70"><span>{time(item.at)}</span>{item.message!.sender_id===user.id&&(item.message!.read_at?<CheckCheck className="h-3.5 w-3.5 text-sky-300"/>:<Check className="h-3.5 w-3.5"/>)}</div></div></div>:<div key={`c-${item.call!.id}`} className={`flex ${item.call!.caller_id===user.id?'justify-end':'justify-start'}`}><div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-xs text-gray-300"><div className="flex items-center gap-2"><Phone className="h-3.5 w-3.5"/>{item.call!.call_type==='video'?'Video':'Voice'} call</div><div className="mt-1 text-[10px] text-gray-500">{item.call!.status} • {dateTime(item.at)}{item.call!.duration_seconds!=null?` • ${item.call!.duration_seconds}s`:''}</div></div></div>)}</div>}
      <div ref={bottom}/>
     </div>
     {blocked?<div className="border-t border-white/10 px-4 py-4 text-center text-sm text-gray-500">You blocked this contact. Unblock them to send messages.</div>:<form onSubmit={send} className="flex items-center gap-2 border-t border-white/10 px-4 py-3"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Type a message" className="min-w-0 flex-1 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none"/><button disabled={busy||!text.trim()} className="rounded-full bg-accent-500 p-3 text-white disabled:opacity-40"><Send className="h-4 w-4"/></button></form>}
    </>}
   </main>
  </div>
  {addOpen&&<div className="absolute inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-ink-900 p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold text-white">Add contact</h2><p className="mt-1 text-xs text-gray-500">Enter the person directly. Avelixa will not show a global user directory.</p></div><button onClick={()=>setAddOpen(false)}><X className="h-5 w-5 text-gray-400"/></button></div><div className="mt-5 space-y-3"><input value={contactName} onChange={e=>setContactName(e.target.value)} placeholder="Contact name" className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none"/><input value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="Email address" type="email" className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none"/>{lookupBusy&&<div className="text-xs text-gray-500">Checking Avelixa…</div>}{identifier.trim()&&!lookupBusy&&<div className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm">{found?<><div className="flex items-center gap-3"><Avatar person={found} size="h-9 w-9"/><div><div className="font-medium text-white">{displayName(found)}</div><div className="text-xs text-gray-500">{found.is_online?'Online':'Offline'}</div></div></div><button onClick={()=>void addContact()} disabled={busy} className="mt-3 w-full rounded-xl bg-accent-500 py-2.5 text-sm font-semibold text-white">Save and open chat</button></>:<><div className="text-gray-300">This email is not registered on Avelixa.</div><div className="mt-1 text-xs text-gray-500">Invite {contactName||'this person'} to join Avelixa and chat with you.</div><button onClick={()=>{setNotice(`Invitation prepared for ${identifier.trim()}. The recipient will need to complete Avelixa account setup before chatting.`);setAddOpen(false)}} className="mt-3 w-full rounded-xl border border-accent-500/30 bg-accent-500/10 py-2.5 text-sm font-semibold text-accent-300">Invite to Avelixa</button></>}</div>}</div></div></div>}
  {incoming&&<CallOverlayV2 call={{id:incoming.id,callType:incoming.call_type,callerId:incoming.caller_id,calleeId:incoming.callee_id,remoteName:displayName(incomingPerson),isIncoming:true,directConversationId:incoming.direct_conversation_id}} onClose={()=>setIncoming(null)}/>} 
  {activeCall&&<CallOverlayV2 call={activeCall} onClose={()=>setActiveCall(null)}/>} 
 </div>;
}
function MessageCircleIcon(){return <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-accent-500/10 text-accent-300"><svg viewBox="0 0 24 24" className="h-8 w-8" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M21 11.5a8.38 8.38 0 0 1-9 8.5 9.77 9.77 0 0 1-4-.8L3 21l1.8-4A8.4 8.4 0 0 1 3 11.5 8.5 8.5 0 0 1 12 3a8.5 8.5 0 0 1 9 8.5Z"/></svg></div>}
