import { FormEvent, useEffect, useState } from 'react';
import { Loader2, Lock } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../../lib/supabase';

export default function SetPassword(){
 const navigate=useNavigate(); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [checking,setChecking]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(!data.session)setError('This invitation link is invalid or has expired. Please request a new invitation.');setChecking(false)}).catch(()=>{setError('This invitation link could not be verified.');setChecking(false)})},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');if(password.length<8){setError('Your password must be at least 8 characters long.');return}if(password!==confirm){setError('The passwords do not match.');return}setSaving(true);const {error:e2}=await supabase.auth.updateUser({password});if(e2)setError(e2.message);else navigate('/portal/messages');setSaving(false)};
 if(checking)return <div className="flex min-h-screen items-center justify-center bg-ink-950"><Loader2 className="h-7 w-7 animate-spin text-accent-400"/></div>;
 return <div className="flex min-h-screen items-center justify-center bg-ink-950 px-4"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-ink-900 p-7 shadow-2xl"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-accent-500/10"><Lock className="h-7 w-7 text-accent-400"/></div><h1 className="mt-5 text-center text-2xl font-semibold text-white">Create your Avelixa password</h1><p className="mt-2 text-center text-sm text-gray-400">Your account was invited to Avelixa. Set a password to finish your account setup and start chatting.</p>{error&&<div className="mt-5 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</div>}{!error&&<form onSubmit={submit} className="mt-6 space-y-4"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" minLength={8} required className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none"/><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirm password" minLength={8} required className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none"/><button disabled={saving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-accent-500 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Finish setup</button></form>}{error&&<button onClick={()=>navigate('/login')} className="mt-5 w-full rounded-xl border border-white/10 py-3 text-sm text-gray-300">Back to login</button>}</div></div>;
}
