import { ChangeEvent, FormEvent, useEffect, useRef, useState } from 'react';
import { ArrowLeft, Bell, Camera, Loader2, Save, ShieldCheck, Volume2, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../lib/auth';

type Profile={id:string;email:string;full_name:string|null;avatar_url:string|null};
type Prefs={user_id:string;message_notifications:boolean;call_notifications:boolean;sound_enabled:boolean;vibration_enabled:boolean;message_sound_url:string|null;voice_ringtone_url:string|null;video_ringtone_url:string|null};
type SoundKey='message_sound_url'|'voice_ringtone_url'|'video_ringtone_url';
const defaults=(id:string):Prefs=>({user_id:id,message_notifications:true,call_notifications:true,sound_enabled:true,vibration_enabled:true,message_sound_url:null,voice_ringtone_url:null,video_ringtone_url:null});
const errorText=(e:unknown)=>{if(e&&typeof e==='object'){const x=e as any;return [x.message,x.details,x.hint,x.code&&`Code: ${x.code}`].filter(Boolean).join(' • ')||'The operation failed.'}return String(e||'The operation failed.')};

export default function SettingsV2(){
 const {user,activeWorkspace}=useAuth(); const fileRef=useRef<HTMLInputElement>(null);
 const [profile,setProfile]=useState<Profile|null>(null),[name,setName]=useState(''),[editing,setEditing]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false);
 const [prefs,setPrefs]=useState<Prefs|null>(null),[savingPrefs,setSavingPrefs]=useState(false),[soundBusy,setSoundBusy]=useState<SoundKey|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[passwordBusy,setPasswordBusy]=useState(false),[passwordMessage,setPasswordMessage]=useState(''),[passwordError,setPasswordError]=useState('');
 useEffect(()=>{if(!user?.id){setLoading(false);return}let alive=true;(async()=>{const [{data:p,error:pe},{data:pr}]=await Promise.all([supabase.from('profiles').select('id,email,full_name,avatar_url').eq('id',user.id).maybeSingle(),supabase.from('user_notification_preferences').select('*').eq('user_id',user.id).maybeSingle()]);if(!alive)return;if(pe)setError(errorText(pe));if(p){const row=p as Profile;setProfile(row);setName(row.full_name||'')}setPrefs((pr as Prefs|null)||defaults(user.id));setLoading(false)})();return()=>{alive=false}},[user?.id]);
 const saveProfile=async(e:FormEvent)=>{e.preventDefault();if(!user?.id||!profile)return;setSaving(true);setError('');setNotice('');try{const fullName=name.trim();const {data,error:profileError}=await supabase.from('profiles').update({full_name:fullName||null,updated_at:new Date().toISOString()}).eq('id',user.id).select('id,email,full_name,avatar_url').maybeSingle();if(profileError)throw profileError;if(!data)throw new Error('Your profile was not updated. Please check that your account has permission to edit its profile.');setProfile(data as Profile);setName((data as Profile).full_name||'');setEditing(false);setNotice('Your profile information has been updated.')}catch(e){setError(errorText(e))}finally{setSaving(false)}};
 const uploadAvatar=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!user?.id)return;setError('');setNotice('');if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)){setError('Choose a JPG, PNG, WebP, or GIF image.');return}if(file.size>5*1024*1024){setError('Profile pictures must be 5 MB or smaller.');return}setUploading(true);try{const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${user.id}/${crypto.randomUUID()}.${ext}`;const {error:e1}=await supabase.storage.from('profile-avatars').upload(path,file,{upsert:false,contentType:file.type,cacheControl:'3600'});if(e1)throw e1;const {data:urlData}=supabase.storage.from('profile-avatars').getPublicUrl(path);const {data,error:e2}=await supabase.from('profiles').update({avatar_url:urlData.publicUrl,updated_at:new Date().toISOString()}).eq('id',user.id).select('id,email,full_name,avatar_url').maybeSingle();if(e2)throw e2;if(!data)throw new Error('The picture uploaded but the profile could not be updated.');setProfile(data as Profile);setNotice('Profile picture updated successfully.')}catch(e){setError(errorText(e))}finally{setUploading(false);e.currentTarget.value=''}};
 const uploadSound=async(field:SoundKey,file:File)=>{if(!user?.id)return;if(file.size>3*1024*1024){setError('Custom sounds must be 3 MB or smaller.');return}setSoundBusy(field);setError('');try{const ext=file.name.split('.').pop()?.toLowerCase()||'mp3';const path=`${user.id}/${field}-${crypto.randomUUID()}.${ext}`;const {error:e}=await supabase.storage.from('notification-sounds').upload(path,file,{upsert:false,contentType:file.type,cacheControl:'3600'});if(e)throw e;const {data}=supabase.storage.from('notification-sounds').getPublicUrl(path);setPrefs(p=>p?{...p,[field]:data.publicUrl}:p);setNotice('Custom sound updated. Save notification settings to keep it.')}catch(e){setError(errorText(e))}finally{setSoundBusy(null)}};
 const savePrefs=async()=>{if(!user?.id||!prefs)return;setSavingPrefs(true);setError('');try{const {data,error:prefsError}=await supabase.from('user_notification_preferences').upsert({...prefs,user_id:user.id,updated_at:new Date().toISOString()},{onConflict:'user_id'}).select('*').single();if(prefsError)throw prefsError;setPrefs(data as Prefs);setNotice('Notification settings saved.')}catch(e){setError(errorText(e))}finally{setSavingPrefs(false)}};
 const changePassword=async(e:FormEvent)=>{e.preventDefault();setPasswordMessage('');setPasswordError('');if(!user?.email){setPasswordError('Account email unavailable.');return}if(newPassword.length<8){setPasswordError('New password must be at least 8 characters.');return}if(newPassword!==confirmPassword){setPasswordError('Passwords do not match.');return}setPasswordBusy(true);try{const {error:v}=await supabase.auth.signInWithPassword({email:user.email,password:currentPassword});if(v)throw new Error('Current password is incorrect.');const {error:u}=await supabase.auth.updateUser({password:newPassword});if(u)throw u;setCurrentPassword('');setNewPassword('');setConfirmPassword('');setPasswordMessage('Password changed successfully.')}catch(e){setPasswordError(errorText(e))}finally{setPasswordBusy(false)}};
 if(loading)return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-accent-400"/></div>;
 const avatar=profile?.avatar_url||''; const initials=(name||user?.email||'U').trim().charAt(0).toUpperCase(); const sounds:[SoundKey,string][]=[['message_sound_url','Message sound'],['voice_ringtone_url','Voice-call ringtone'],['video_ringtone_url','Video-call ringtone']];
 const backPath=activeWorkspace==='owner'?'/portal/owner':activeWorkspace==='admin'?'/portal/admin':activeWorkspace==='operator'?'/portal/operator':activeWorkspace==='connector'?'/portal/connector':'/portal';
 return <div className="space-y-6"><div><Link to={backPath} className="mb-4 inline-flex items-center gap-2 text-sm font-medium text-gray-400 transition-colors hover:text-white"><ArrowLeft className="h-4 w-4"/>Back to {activeWorkspace ? `${activeWorkspace.charAt(0).toUpperCase()}${activeWorkspace.slice(1)} Dashboard` : 'Portal'}</Link><h1 className="text-3xl font-semibold text-white">Settings</h1><p className="mt-2 text-gray-400">Manage your profile, notifications, sounds and account security.</p></div>{(notice||error)&&<div className={`rounded-xl border px-4 py-3 text-sm ${error?'border-red-500/20 bg-red-500/10 text-red-300':'border-emerald-500/20 bg-emerald-500/10 text-emerald-300'}`}>{error||notice}</div>}
 <section className="glass rounded-2xl border border-ink-800/50 p-6 sm:p-8"><h2 className="text-xl font-medium text-white">Profile</h2><div className="mt-6 flex flex-col gap-5 sm:flex-row sm:items-center"><div className="relative h-24 w-24"><div className="h-24 w-24 overflow-hidden rounded-full border border-white/10 bg-accent-500/10 flex items-center justify-center text-2xl font-semibold text-accent-300">{avatar?<img src={avatar} className="h-full w-full object-cover" alt="Profile"/>:initials}</div><button type="button" onClick={()=>fileRef.current?.click()} disabled={uploading} className="absolute -bottom-1 -right-1 rounded-full bg-accent-500 p-2 text-white">{uploading?<Loader2 className="h-4 w-4 animate-spin"/>:<Camera className="h-4 w-4"/>}</button><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={uploadAvatar} className="hidden"/></div><div><div className="font-semibold text-white">{name||'No display name'}</div><div className="text-sm text-gray-400">{user?.email}</div><button type="button" onClick={()=>fileRef.current?.click()} className="mt-3 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs text-gray-300">{uploading?'Uploading…':'Change picture'}</button></div></div><form onSubmit={saveProfile} className="mt-7 space-y-4"><label className="block text-sm text-gray-300">Full name<input value={name} onChange={e=>setName(e.target.value)} disabled={!editing||saving} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none focus:border-accent-500 disabled:opacity-60"/></label>{!editing?<button type="button" onClick={()=>{setError('');setNotice('');setEditing(true)}} className="rounded-xl bg-accent-600 px-4 py-2.5 text-sm text-white">Edit profile</button>:<div className="flex gap-3"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-accent-600 px-4 py-2.5 text-sm text-white">{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}<Save className="h-4 w-4"/>Save changes</button><button type="button" onClick={()=>{setName(profile?.full_name||'');setEditing(false)}} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm text-gray-300"><X className="h-4 w-4"/>Cancel</button></div>}</form></section>
 <section className="glass rounded-2xl border border-ink-800/50 p-6"><div className="flex items-center gap-3"><Bell className="h-5 w-5 text-accent-400"/><h2 className="text-lg font-medium text-white">Notifications & Sounds</h2></div>{prefs&&<div className="mt-6 space-y-4"><label className="flex justify-between gap-4 text-sm text-white">Message notifications<input type="checkbox" checked={prefs.message_notifications} onChange={e=>setPrefs({...prefs,message_notifications:e.target.checked})}/></label><label className="flex justify-between gap-4 text-sm text-white">Call notifications<input type="checkbox" checked={prefs.call_notifications} onChange={e=>setPrefs({...prefs,call_notifications:e.target.checked})}/></label><label className="flex justify-between gap-4 text-sm text-white">Sounds<input type="checkbox" checked={prefs.sound_enabled} onChange={e=>setPrefs({...prefs,sound_enabled:e.target.checked})}/></label><label className="flex justify-between gap-4 text-sm text-white">Vibration<input type="checkbox" checked={prefs.vibration_enabled} onChange={e=>setPrefs({...prefs,vibration_enabled:e.target.checked})}/></label><div className="space-y-3">{sounds.map(([field,label])=><div key={field} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 p-3"><div className="flex min-w-0 items-center gap-2 text-sm text-gray-200"><Volume2 className="h-4 w-4 text-accent-400"/>{label}</div><label className="cursor-pointer rounded-lg border border-white/10 px-3 py-2 text-xs text-gray-300">{soundBusy===field?'Uploading…':'Choose audio'}<input type="file" accept="audio/*" className="hidden" disabled={!!soundBusy} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadSound(field,f);e.currentTarget.value=''}}/></label></div>)}</div><button type="button" onClick={()=>void savePrefs()} disabled={savingPrefs} className="rounded-xl bg-accent-600 px-4 py-2.5 text-sm text-white">{savingPrefs?'Saving…':'Save notification settings'}</button></div>}</section>
 <section className="glass rounded-2xl border border-ink-800/50 p-6"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-accent-400"/><h2 className="text-lg font-medium text-white">Password & Security</h2></div><form onSubmit={changePassword} className="mt-5 space-y-3"><input required type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} placeholder="Current password" className="w-full rounded-xl bg-white/5 px-4 py-3 text-sm text-white"/><input required type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="New password" className="w-full rounded-xl bg-white/5 px-4 py-3 text-sm text-white"/><input required type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Confirm new password" className="w-full rounded-xl bg-white/5 px-4 py-3 text-sm text-white"/><button disabled={passwordBusy} className="rounded-xl bg-accent-600 px-4 py-2.5 text-sm text-white">{passwordBusy?'Changing…':'Change password'}</button></form>{passwordMessage&&<div className="mt-3 text-sm text-emerald-300">{passwordMessage}</div>}{passwordError&&<div className="mt-3 text-sm text-red-300">{passwordError}</div>}</section></div>;
}
