import type { BusinessInformation, CreationProject, WebsiteGenerationOutput, WebsiteSectionId, WebsiteSpecification, WebsiteTemplate, WebsiteTheme } from './types.ts';
import { WEBSITE_SECTIONS } from './types.ts';
import { templateSections } from './templates.ts';

const clean = (value?: string | null) => value?.trim() || '';
const list = (values?: string[]) => (values || []).map((value) => value.trim()).filter(Boolean);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === 'object' && !Array.isArray(value);
const clone = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
export type WebsiteGenerationFailureCode = 'validation' | 'template' | 'generation' | 'rendering';
export interface WebsiteGenerationSuccess { ok: true; artifact: WebsiteSpecification; template: WebsiteTemplate; }
export interface WebsiteGenerationFailure { ok: false; code: WebsiteGenerationFailureCode; errors: string[]; }
export type WebsiteGenerationResult = WebsiteGenerationSuccess | WebsiteGenerationFailure;
export interface WebsiteOutputGenerationSuccess { ok: true; output: WebsiteGenerationOutput; }
export interface WebsiteOutputGenerationFailure { ok: false; code: WebsiteGenerationFailureCode; errors: string[]; }
export type WebsiteOutputGenerationResult = WebsiteOutputGenerationSuccess | WebsiteOutputGenerationFailure;

export function validateBusinessInformation(business: BusinessInformation): string[] {
  const errors: string[] = [];
  if (!business || !isRecord(business)) return ['Business information is required.'];
  if (!clean(business.businessName)) errors.push('Business name is required.');
  if (business.email && !/^\S+@\S+\.\S+$/.test(business.email.trim())) errors.push('Email address is invalid.');
  return errors;
}
function isWebsiteSectionId(value: unknown): value is WebsiteSectionId { return typeof value === 'string' && (WEBSITE_SECTIONS as readonly string[]).includes(value); }
function validThemeValue(value: unknown, field: string, errors: string[]) { if (typeof value !== 'string' || !value.trim()) errors.push(`Theme ${field} is invalid.`); }

export function validateWebsiteSpecification(specification: WebsiteSpecification, template?: WebsiteTemplate | null): string[] {
  const errors: string[] = [];
  if (!specification || !isRecord(specification)) return ['Website specification is required.'];
  if (specification.version !== 1) errors.push('Unsupported WebsiteSpecification version.');
  errors.push(...validateBusinessInformation(specification.business));
  if (!isRecord(specification.template) || !clean(specification.template.id) || !clean(specification.template.slug)) errors.push('Website template reference is invalid.');
  if (!Array.isArray(specification.sections) || specification.sections.length === 0) errors.push('Website sections are required.');
  else { const seen = new Set<string>(); for (const section of specification.sections) { if (!isWebsiteSectionId(section)) errors.push(`Unsupported website section: ${String(section)}.`); else if (seen.has(section)) errors.push(`Duplicate website section: ${section}.`); else seen.add(section); } }
  if (!Array.isArray(specification.navigation)) errors.push('Website navigation is invalid.');
  else { const seen = new Set<string>(); for (const item of specification.navigation) { if (!isRecord(item) || !clean(String(item.label || '')) || !isWebsiteSectionId(item.section)) { errors.push('Website navigation contains an invalid item.'); continue; } if (!specification.sections.includes(item.section)) errors.push(`Navigation target is not enabled: ${item.section}.`); if (seen.has(item.section)) errors.push(`Duplicate navigation target: ${item.section}.`); seen.add(item.section); } }
  if (!isRecord(specification.theme)) errors.push('Website theme is invalid.');
  else for (const field of ['primary', 'secondary', 'accent', 'surface', 'text', 'muted', 'headingFont', 'bodyFont']) validThemeValue(specification.theme[field as keyof WebsiteTheme], field, errors);
  if (!isRecord(specification.content)) errors.push('Website content is invalid.');
  else for (const key of Object.keys(specification.content)) if (!isWebsiteSectionId(key)) errors.push(`Unsupported website content section: ${key}.`);
  if (!isRecord(specification.attribution) || typeof specification.attribution.enabled !== 'boolean') errors.push('Website attribution configuration is invalid.');
  if (template) { if (specification.template.id !== template.id || specification.template.slug !== template.slug) errors.push('Website specification template does not match the selected template.'); const allowed = new Set(template.sections); for (const section of specification.sections) if (!allowed.has(section)) errors.push(`Section ${section} is not supported by template ${template.slug}.`); }
  return errors;
}

function normalizeBusiness(business: BusinessInformation): BusinessInformation {
  const socialLinks = Object.fromEntries(Object.entries(business.socialLinks || {}).map(([key, value]) => [key.trim(), String(value).trim()] as const).filter(([key, value]) => key && value).sort(([a], [b]) => a.localeCompare(b)));
  return { ...business, businessName: clean(business.businessName), industry: clean(business.industry), businessDescription: clean(business.businessDescription), services: list(business.services), products: list(business.products), targetAudience: clean(business.targetAudience), location: clean(business.location), phone: clean(business.phone), email: clean(business.email), whatsapp: clean(business.whatsapp), socialLinks, logoUrl: clean(business.logoUrl), imagery: list(business.imagery), websiteType: clean(business.websiteType), specialRequirements: clean(business.specialRequirements) };
}
export function normalizeWebsiteSpecification(specification: WebsiteSpecification, template: WebsiteTemplate): WebsiteSpecification {
  const normalized = clone(specification); const sections = [...new Set(normalized.sections)]; const existingLabels = new Map(normalized.navigation.map((item) => [item.section, clean(item.label)])); const structural = new Set<WebsiteSectionId>(['navbar', 'hero', 'footer']);
  normalized.template = { id: template.id, slug: template.slug, name: template.name, visual_style: template.visual_style }; normalized.business = normalizeBusiness(normalized.business); normalized.sections = sections;
  normalized.navigation = sections.filter((section) => !structural.has(section)).map((section) => ({ label: existingLabels.get(section) || section.charAt(0).toUpperCase() + section.slice(1), section }));
  normalized.theme = { primary: clean(normalized.theme.primary), secondary: clean(normalized.theme.secondary), accent: clean(normalized.theme.accent), surface: clean(normalized.theme.surface), text: clean(normalized.theme.text), muted: clean(normalized.theme.muted), headingFont: clean(normalized.theme.headingFont), bodyFont: clean(normalized.theme.bodyFont) };
  normalized.attribution = { enabled: normalized.attribution.enabled, label: clean(normalized.attribution.label) || 'Made with Avelixa' }; return normalized;
}
export function resolveWebsiteTemplate(templateId: string, templates: readonly WebsiteTemplate[]): WebsiteTemplate | null { return templates.find((template) => template.id === templateId && template.is_active) || null; }
export function generateWebsiteFromSpecification(specification: WebsiteSpecification, template: WebsiteTemplate): WebsiteGenerationResult { const validationErrors = validateWebsiteSpecification(specification, template); if (validationErrors.length) return { ok: false, code: 'validation', errors: validationErrors }; try { return { ok: true, artifact: normalizeWebsiteSpecification(specification, template), template }; } catch { return { ok: false, code: 'generation', errors: ['The website could not be generated from the supplied specification.'] }; } }
export function generateWebsiteFromCreationProject(project: CreationProject, templates: readonly WebsiteTemplate[]): WebsiteGenerationResult { if (!project || !project.id) return { ok: false, code: 'validation', errors: ['Creation project is invalid.'] }; if (!project.specification) return { ok: false, code: 'validation', errors: ['This creation project does not have a saved website specification.'] }; if (!project.selected_template_id) return { ok: false, code: 'template', errors: ['This creation project does not have a selected template.'] }; const template = resolveWebsiteTemplate(project.selected_template_id, templates); if (!template) return { ok: false, code: 'template', errors: ['The selected website template is unavailable.'] }; return generateWebsiteFromSpecification(project.specification, template); }
function canonicalize(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonicalize); if (isRecord(value)) return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonicalize(value[key])])); return value; }
function stableSerialize(value: unknown): string { return JSON.stringify(canonicalize(value)); }
function hashString(value: string): string { let hash = 2166136261; for (let index = 0; index < value.length; index += 1) { hash ^= value.charCodeAt(index); hash = Math.imul(hash, 16777619); } return (hash >>> 0).toString(16).padStart(8, '0'); }
export function createWebsiteOutputVersion(specification: WebsiteSpecification): string { return hashString(stableSerialize(specification)); }
export function createWebsiteOutputIdentity(creationProjectId: string, specification: WebsiteSpecification): string { return `website-${hashString(`${creationProjectId}:${stableSerialize(specification)}`)}`; }
export function generateWebsiteOutputFromSpecification(specification: WebsiteSpecification, template: WebsiteTemplate, creationProjectId: string, generatedAt = new Date().toISOString(), previewPath: string | null = null): WebsiteOutputGenerationResult { if (!clean(creationProjectId)) return { ok: false, code: 'validation', errors: ['Creation project is invalid.'] }; const generated = generateWebsiteFromSpecification(specification, template); if (!generated.ok) return generated; const outputVersion = createWebsiteOutputVersion(generated.artifact); return { ok: true, output: { id: createWebsiteOutputIdentity(creationProjectId, generated.artifact), creationProjectId, specification: generated.artifact, template: generated.template, status: 'generated', generatedAt, outputVersion, previewPath } }; }
export function generateWebsiteOutputFromCreationProject(project: CreationProject, templates: readonly WebsiteTemplate[], generatedAt = new Date().toISOString()): WebsiteOutputGenerationResult { if (!project || !clean(project.id)) return { ok: false, code: 'validation', errors: ['Creation project is invalid.'] }; const generated = generateWebsiteFromCreationProject(project, templates); if (!generated.ok) return generated; const previewPath = project.public_preview_token && project.preview_enabled ? `/preview/${encodeURIComponent(project.public_preview_token)}` : null; return generateWebsiteOutputFromSpecification(generated.artifact, generated.template, project.id, generatedAt, previewPath); }
function themeFor(template: WebsiteTemplate, business: BusinessInformation): WebsiteTheme { const colors = business.brandColors || {}; const direction = template.color_direction || {}; return { primary: colors.primary || direction.primary || '#111827', secondary: colors.secondary || direction.secondary || '#334155', accent: colors.accent || direction.accent || '#7c3aed', surface: colors.surface || direction.surface || '#f8fafc', text: '#111827', muted: '#64748b', headingFont: template.typography?.heading || 'modern-sans', bodyFont: template.typography?.body || 'clean-sans' }; }
const navigationLabel: Record<WebsiteSectionId, string> = { navbar: 'Home', hero: 'Home', about: 'About', services: 'Services', products: 'Products', gallery: 'Gallery', stats: 'Impact', story: 'Story', values: 'Values', process: 'Process', portfolio: 'Work', team: 'Team', offers: 'Offers', testimonials: 'Testimonials', pricing: 'Pricing', faq: 'FAQ', hours: 'Hours', location: 'Location', social: 'Social', finalCta: 'Get started', contact: 'Contact', footer: 'Contact' };
const stableDemoAssets = ['/images/template-modern-business.svg', '/images/template-premium-minimal.svg', '/images/template-local-commerce.svg', '/images/template-creative-studio.svg', '/images/template-trusted-community.svg'];
const styleDemoBusiness: Record<string, BusinessInformation> = {
  'editorial-modern': { businessName: 'Northstar Advisory', industry: 'Business Consulting', businessDescription: 'Northstar Advisory helps ambitious teams turn complex growth questions into focused decisions, practical systems, and measurable progress.', targetAudience: 'Founders and leadership teams', location: 'Nairobi, Kenya', phone: '+254 700 410 218', email: 'hello@northstar-demo.co.ke', whatsapp: '+254700410218', services: ['Growth strategy', 'Operations design', 'Leadership workshops'], imagery: [stableDemoAssets[0]] },
  'premium-minimal': { businessName: 'Atelier Noma', industry: 'Interior & Lifestyle', businessDescription: 'Atelier Noma creates calm, considered interiors and objects for people who value material, proportion, and enduring design.', targetAudience: 'Private clients and boutique hospitality', location: 'Nairobi, Kenya', email: 'studio@ateliernoma.example', services: ['Interior direction', 'Spatial styling', 'Bespoke sourcing'], imagery: [stableDemoAssets[1]] },
  'warm-commerce': { businessName: 'Maua Market', industry: 'Local Retail', businessDescription: 'Maua Market brings thoughtful everyday goods, fresh seasonal finds, and warm service together in one neighborhood destination.', targetAudience: 'Neighborhood families and gift buyers', location: 'Kilimani, Nairobi', phone: '+254 711 240 662', email: 'hello@mauamarket.example', whatsapp: '+254711240662', products: ['Seasonal flower bundles', 'Home fragrance', 'Curated gift boxes'], services: ['Same-day local delivery', 'Gift wrapping', 'Custom orders'], imagery: [stableDemoAssets[2]] },
  'creative-bold': { businessName: 'Frame & Form', industry: 'Creative Studio', businessDescription: 'Frame & Form is a visual studio building sharp identities, campaigns, and digital experiences for brands ready to be remembered.', targetAudience: 'Culture-led brands and founders', location: 'Nairobi, Kenya', email: 'hello@frameandform.example', services: ['Brand identity', 'Campaign direction', 'Digital design'], imagery: [stableDemoAssets[3]] },
  'trusted-community': { businessName: 'BrightPath Community', industry: 'Community Organization', businessDescription: 'BrightPath Community creates practical learning, mentorship, and family support programs that help local neighborhoods grow stronger together.', targetAudience: 'Young people, families, and community partners', location: 'Eastlands, Nairobi', phone: '+254 720 315 904', email: 'hello@brightpath.example', whatsapp: '+254720315904', services: ['Youth mentorship', 'Family support', 'Skills workshops'], imagery: [stableDemoAssets[4]] },
};

function demoSections(style: string): WebsiteSectionId[] {
  const map: Record<string, WebsiteSectionId[]> = {
    'editorial-modern': ['navbar','hero','stats','about','services','process','portfolio','testimonials','team','finalCta','contact','footer'],
    'premium-minimal': ['navbar','hero','story','services','gallery','values','testimonials','contact','footer'],
    'warm-commerce': ['navbar','hero','offers','products','services','gallery','hours','location','testimonials','finalCta','contact','footer'],
    'creative-bold': ['navbar','hero','portfolio','about','services','gallery','testimonials','finalCta','contact','footer'],
    'trusted-community': ['navbar','hero','about','services','stats','testimonials','faq','location','contact','footer'],
  };
  return map[style] || map['editorial-modern'];
}

function demoContent(style: string, business: BusinessInformation) {
  const name = business.businessName;
  const common = {
    hero: { eyebrow: business.industry, title: name, subtitle: business.businessDescription, cta: style === 'warm-commerce' ? 'Visit the shop' : style === 'creative-bold' ? 'Start a project' : 'Start a conversation' },
    contact: { phone: business.phone || '', email: business.email || '', whatsapp: business.whatsapp || '' },
    location: { address: business.location || '' }, footer: { businessName: name },
  };
  const contentByStyle: Record<string, Record<string, unknown>> = {
    'editorial-modern': { ...common, stats: { items: [{ value: '3.4×', label: 'Average planning clarity', detail: 'from focused decision frameworks' }, { value: '12 wk', label: 'Typical transformation sprint', detail: 'from diagnosis to delivery' }, { value: '94%', label: 'Leadership adoption', detail: 'across facilitated programs' }] }, about: { title: 'Clarity first. Momentum follows.', body: 'Northstar brings strategy, operating rhythm, and leadership alignment into one practical engagement. The result is a business that can make better decisions and move with confidence.' }, services: { items: ['Growth strategy','Operating model design','Leadership workshops'] }, process: { items: [{ step: '01', title: 'Understand', body: 'We map the real constraints, opportunities, and decisions in front of the team.' }, { step: '02', title: 'Focus', body: 'We turn complexity into a short list of priorities with clear ownership.' }, { step: '03', title: 'Move', body: 'We build the rhythm, tools, and accountability needed to make progress stick.' }] }, portfolio: { items: [{ title: 'Kijani Foods', category: 'Growth strategy', description: 'A sharper route-to-market plan for a fast-growing food brand.', result: '2.1× qualified pipeline' }, { title: 'Aster Health', category: 'Operations', description: 'A simpler operating rhythm across a multi-site service team.', result: '31% faster decisions' }, { title: 'Mara Ventures', category: 'Leadership', description: 'A leadership cadence built for a founder-led investment platform.', result: '12-week alignment sprint' }] }, testimonials: { items: [{ quote: 'Northstar gave our leadership team a language for the decisions we had been circling for months.', author: 'Maya K. — Managing Director' }, { quote: 'The work was rigorous, practical, and immediately useful in the week after the engagement.', author: 'Daniel O. — Founder' }] }, team: { items: [{ name: 'Amara N.', role: 'Strategy Director', bio: 'Growth strategy and operating systems.' }, { name: 'David M.', role: 'Leadership Partner', bio: 'Facilitation and executive alignment.' }, { name: 'Lina K.', role: 'Delivery Lead', bio: 'Implementation and team enablement.' }] }, finalCta: { title: 'Make the next decision easier.', body: 'Bring the complex question. We will help you turn it into a clear path forward.', cta: 'Book a discovery call' } },
    'premium-minimal': { ...common, story: { kicker: 'The studio', title: 'Quiet spaces. Considered details.', body: 'Atelier Noma works between architecture, styling, and sourcing to create spaces that feel collected rather than decorated. Every decision is deliberate, from the first sketch to the final object.', quote: 'A room should hold your attention without asking for it.' }, services: { items: ['Interior direction','Spatial styling','Bespoke sourcing'] }, gallery: { images: [stableDemoAssets[1],stableDemoAssets[0],stableDemoAssets[4]] }, values: { items: [{ title: 'Material honesty', body: 'We choose finishes for how they age, feel, and belong together.' }, { title: 'Measured simplicity', body: 'Less visual noise makes room for the pieces that matter.' }, { title: 'Personal rhythm', body: 'The best interiors reflect the people who live or work inside them.' }] }, testimonials: { items: [{ quote: 'The finished space feels effortless, but every detail has a reason.', author: 'Private residence client' }, { quote: 'A rare combination of restraint, warmth, and absolute attention to detail.', author: 'Boutique hotel partner' }] } },
    'warm-commerce': { ...common, offers: { items: [{ label: 'This week', title: 'Market Box', description: 'A generous mix of seasonal favorites, packed and ready to gift.', price: 'From KSh 2,450', featured: true }, { label: 'Local favorite', title: 'Fresh Friday', description: 'Order before noon for same-day neighborhood delivery.', price: 'Every Friday' }] }, products: { items: [{ name: 'Seasonal flower bundles', price: 'From KSh 1,800', detail: 'Fresh stems, wrapped for the day.' }, { name: 'Home fragrance', price: 'From KSh 1,250', detail: 'Small-batch scents for everyday spaces.' }, { name: 'Curated gift boxes', price: 'From KSh 2,450', detail: 'Thoughtful combinations, ready to give.' }] }, services: { items: ['Same-day local delivery','Gift wrapping','Custom orders'] }, gallery: { images: [stableDemoAssets[2],stableDemoAssets[0],stableDemoAssets[1]] }, hours: { items: [{ day: 'Monday – Friday', hours: '8:00 AM – 7:00 PM' }, { day: 'Saturday', hours: '9:00 AM – 6:00 PM' }, { day: 'Sunday', hours: '10:00 AM – 4:00 PM' }] }, testimonials: { items: [{ quote: 'Beautifully packed, genuinely helpful, and the order arrived right when promised.', author: 'Amina — Kilimani' }, { quote: 'Maua has become our go-to whenever we need a thoughtful gift quickly.', author: 'Brian — Lavington' }] }, finalCta: { title: 'Need something today?', body: 'Message the shop and we will help you choose, personalize, and arrange delivery.', cta: 'Chat on WhatsApp' } },
    'creative-bold': { ...common, portfolio: { items: [{ title: 'Maji / New Rituals', category: 'Brand identity', description: 'A visual system for a new generation of personal care.', result: 'Identity + launch campaign', image: stableDemoAssets[3] }, { title: 'Nuru / City in Motion', category: 'Campaign', description: 'A kinetic campaign language for a culture platform.', result: 'Digital + OOH', image: stableDemoAssets[0] }, { title: 'Soko / Everyday Future', category: 'Digital experience', description: 'A commerce experience built around discovery and speed.', result: 'Product + web', image: stableDemoAssets[2] }] }, about: { title: 'We make brands impossible to ignore.', body: 'Frame & Form combines strategy, identity, and digital craft to give ambitious brands a visual language with enough edge to stand apart and enough structure to scale.' }, services: { items: ['Brand identity','Campaign direction','Digital design'] }, gallery: { images: [stableDemoAssets[3],stableDemoAssets[1],stableDemoAssets[0]] }, testimonials: { items: [{ quote: 'They found the sharpest version of the idea and made the whole team believe in it.', author: 'Founder, consumer brand' }, { quote: 'The new identity finally feels like the scale of the company we are building.', author: 'Creative lead, technology company' }] }, finalCta: { title: 'Have an idea with teeth?', body: 'Let’s turn it into a brand people remember.', cta: 'Start a project' } },
    'trusted-community': { ...common, about: { title: 'Stronger neighborhoods start with practical support.', body: 'BrightPath brings mentorship, family support, and useful skills into spaces where people already gather. Our programs are designed to be welcoming, measurable, and built with the community—not simply for it.' }, services: { items: ['Youth mentorship','Family support','Skills workshops'] }, stats: { items: [{ value: '1,240+', label: 'People reached', detail: 'through community programs' }, { value: '86', label: 'Mentors and facilitators', detail: 'supporting local sessions' }, { value: '18', label: 'Active learning groups', detail: 'meeting across the neighborhood' }] }, testimonials: { items: [{ quote: 'The mentorship gave my daughter confidence and a place to ask questions without feeling judged.', author: 'Parent participant' }, { quote: 'BrightPath makes support practical. You leave with something you can use.', author: 'Community workshop participant' }] }, faq: { items: [{ question: 'Who can join the programs?', answer: 'Programs are open to local young people, families, and community partners according to each program’s schedule and capacity.' }, { question: 'How can I volunteer?', answer: 'Use the contact details below and tell us what skills, time, or community connection you would like to contribute.' }, { question: 'Where do sessions happen?', answer: 'Sessions rotate across accessible community spaces in the neighborhood. Contact us for the current schedule.' }] } },
  };
  return contentByStyle[style] || contentByStyle['editorial-modern'];
}

export function generateWebsiteDemoSpecification(template: WebsiteTemplate, attributionEnabled = true): WebsiteSpecification {
  const style = template.visual_style;
  const business = clone(styleDemoBusiness[style] || styleDemoBusiness['editorial-modern']);
  const sections = demoSections(style);
  const content = demoContent(style, business);
  return normalizeWebsiteSpecification({ version: 1, template: { id: template.id, slug: template.slug, name: template.name, visual_style: template.visual_style }, business, sections, theme: themeFor(template, business), navigation: sections.filter((section) => !['navbar','hero','footer'].includes(section)).map((section) => ({ label: navigationLabel[section], section })), content, attribution: { enabled: attributionEnabled, label: 'Made with Avelixa' } }, template);
}

export function generateWebsiteSpecification(business: BusinessInformation, template: WebsiteTemplate, requestedSections: WebsiteSectionId[] = [], attributionEnabled = true): WebsiteSpecification {
  const errors = validateBusinessInformation(business); if (errors.length) throw new Error(errors.join(' '));
  const sections = templateSections(template, requestedSections); const normalizedBusiness = normalizeBusiness(business); const name = normalizedBusiness.businessName;
  const description = normalizedBusiness.businessDescription || `${name}${normalizedBusiness.industry ? ` is a ${normalizedBusiness.industry.toLowerCase()}` : ''}${normalizedBusiness.location ? ` serving ${normalizedBusiness.location}` : ''}.`;
  const serviceItems = normalizedBusiness.services || []; const productItems = normalizedBusiness.products || [];
  const content: Record<string, unknown> = {
    hero: { eyebrow: normalizedBusiness.industry, title: name, subtitle: description, cta: 'Get in touch' },
    about: { title: `About ${name}`, body: description }, services: { items: serviceItems }, products: { items: productItems }, gallery: { images: normalizedBusiness.imagery || [] },
    stats: { items: [{ value: String(serviceItems.length), label: 'Core services', detail: 'Configured for this website' }, { value: normalizedBusiness.location ? 'Local' : 'Flexible', label: 'Service model', detail: normalizedBusiness.location || 'Based on business information' }] },
    story: { kicker: 'Our story', title: `Built around ${name}`, body: description }, values: { items: [] }, process: { items: [{ step: '01', title: 'Discover', body: 'Clarify goals, audience, and the opportunity.' }, { step: '02', title: 'Shape', body: 'Turn the brief into a focused experience and content structure.' }, { step: '03', title: 'Deliver', body: 'Refine the details and prepare the website for the next stage.' }] }, portfolio: { items: [] }, team: { items: [] }, offers: { items: [] }, testimonials: { items: [] }, pricing: { items: [] }, faq: { items: [] }, hours: { items: [] }, location: { address: normalizedBusiness.location || '' }, social: { items: Object.entries(normalizedBusiness.socialLinks || {}).map(([label, url]) => ({ label, url })) }, finalCta: { title: 'Ready for the next step?', body: 'Start a conversation and turn the brief into a clear plan.', cta: 'Get in touch' }, contact: { phone: normalizedBusiness.phone || '', email: normalizedBusiness.email || '', whatsapp: normalizedBusiness.whatsapp || '' }, footer: { businessName: name },
  };
  if (!normalizedBusiness.imagery?.length) content.gallery = { images: [] };
  const candidate: WebsiteSpecification = { version: 1, template: { id: template.id, slug: template.slug, name: template.name, visual_style: template.visual_style }, business: { ...normalizedBusiness, businessDescription: description }, sections, theme: themeFor(template, normalizedBusiness), navigation: sections.filter((section) => !['navbar','hero','footer'].includes(section)).map((section) => ({ label: navigationLabel[section], section })), content, attribution: { enabled: attributionEnabled, label: 'Made with Avelixa' } };
  const result = generateWebsiteFromSpecification(candidate, template); if (!result.ok) throw new Error(result.errors.join(' ')); return result.artifact;
}

export interface WebsiteGenerationAdapter { generate(input: Parameters<typeof generateWebsiteSpecification>): WebsiteSpecification | Promise<WebsiteSpecification>; }
export const deterministicWebsiteGenerationAdapter: WebsiteGenerationAdapter = { generate: ([business, template, requestedSections, attributionEnabled]) => generateWebsiteSpecification(business, template, requestedSections, attributionEnabled) };