import type { CSSProperties, ReactNode } from 'react';
import type { WebsiteSpecification } from '../../lib/websiteCreation/types';
import { getWebsiteTemplatePresentation } from '../../lib/websiteCreation/presentation';

interface SectionProps { spec: WebsiteSpecification; }
type StyleKey = ReturnType<typeof getWebsiteTemplatePresentation>['styleKey'];
const Section = ({ id, children, className = '', style }: { id: string; children: ReactNode; className?: string; style?: CSSProperties }) => <section id={id} className={`px-5 py-16 sm:px-8 md:px-10 md:py-24 ${className}`} style={style}>{children}</section>;
const Container = ({ children, className = '' }: { children: ReactNode; className?: string }) => <div className={`mx-auto w-full max-w-6xl ${className}`}>{children}</div>;
const styleOf = (spec: WebsiteSpecification): StyleKey => getWebsiteTemplatePresentation(spec).styleKey;
const initials = (name: string) => name.trim().charAt(0).toUpperCase() || 'A';
const heroImage = (spec: WebsiteSpecification) => spec.business.imagery?.find(Boolean) || '';
const services = (spec: WebsiteSpecification) => ((spec.content.services as { items?: unknown[] } | undefined)?.items || []).map(String).filter(Boolean);
const products = (spec: WebsiteSpecification) => ((spec.content.products as { items?: unknown[] } | undefined)?.items || []).map(String).filter(Boolean);
const gallery = (spec: WebsiteSpecification) => ((spec.content.gallery as { images?: unknown[] } | undefined)?.images || []).map(String).filter(Boolean);
const testimonials = (spec: WebsiteSpecification) => ((spec.content.testimonials as { items?: { quote?: string; author?: string }[] } | undefined)?.items || []).filter((item) => item?.quote || item?.author);
const pricing = (spec: WebsiteSpecification) => ((spec.content.pricing as { items?: { name?: string; price?: string }[] } | undefined)?.items || []).filter((item) => item?.name || item?.price);
const faqs = (spec: WebsiteSpecification) => ((spec.content.faq as { items?: { question?: string; answer?: string }[] } | undefined)?.items || []).filter((item) => item?.question || item?.answer);

function Brand({ spec, light = false }: { spec: WebsiteSpecification; light?: boolean }) {
  return <div className="flex min-w-0 items-center gap-3 font-semibold" style={{ color: light ? '#fff' : spec.theme.primary }}>
    {spec.business.logoUrl ? <img src={spec.business.logoUrl} alt="" className="h-10 w-10 shrink-0 rounded-xl object-cover" /> : <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl text-sm font-black" style={{ background: spec.theme.accent, color: '#fff' }}>{initials(spec.business.businessName)}</span>}
    <span className="min-w-0 break-words text-sm sm:text-base">{spec.business.businessName}</span>
  </div>;
}

export function Navbar({ spec }: SectionProps) {
  const style = styleOf(spec);
  const links = spec.navigation.slice(0, 6);
  const dark = style === 'creative-bold';
  return <header className={`sticky top-0 z-20 border-b px-5 py-4 backdrop-blur-xl sm:px-8 ${dark ? 'border-white/10 bg-slate-950/90' : 'border-black/5 bg-white/90'}`}>
    <Container><div className="flex min-w-0 items-center justify-between gap-4"><Brand spec={spec} light={dark} />
      <nav className="hidden min-w-0 flex-wrap justify-end gap-5 text-sm md:flex">{links.map((item) => <a key={item.section} href={`#${item.section}`} className={`break-words transition-opacity hover:opacity-60 ${dark ? 'text-slate-200' : 'text-slate-600'}`}>{item.label}</a>)}</nav>
      <details className="relative md:hidden"><summary className={`cursor-pointer list-none rounded-full border px-4 py-2 text-xs font-bold ${dark ? 'border-white/15 text-white' : 'border-black/10 text-slate-700'}`}>Menu</summary><div className={`absolute right-0 mt-3 w-52 rounded-2xl border p-3 shadow-2xl ${dark ? 'border-white/10 bg-slate-900' : 'border-black/5 bg-white'}`}>{links.map((item) => <a key={item.section} href={`#${item.section}`} className={`block rounded-xl px-3 py-2.5 text-sm ${dark ? 'text-slate-200 hover:bg-white/5' : 'text-slate-700 hover:bg-slate-50'}`}>{item.label}</a>)}</div></details>
    </div></Container>
  </header>;
}

export function Hero({ spec }: SectionProps) {
  const style = styleOf(spec); const c = (spec.content.hero || {}) as { eyebrow?: string; title?: string; subtitle?: string; cta?: string }; const image = heroImage(spec); const target = spec.sections.includes('contact') ? '#contact' : spec.sections.find((s) => !['navbar', 'hero', 'footer'].includes(s)) ? `#${spec.sections.find((s) => !['navbar', 'hero', 'footer'].includes(s))}` : '#footer';
  if (style === 'creative-bold') return <Section id="hero" className="relative overflow-hidden bg-slate-950 text-white" style={{ background: `radial-gradient(circle at 80% 20%, ${spec.theme.accent}33, transparent 34%), linear-gradient(135deg, ${spec.theme.primary}, #050816)` }}><Container><div className="grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div className="pt-8 md:pt-14"><div className="mb-6 text-xs font-black uppercase tracking-[.28em] text-cyan-300">{c.eyebrow || 'Creative presence'}</div><h1 className="max-w-4xl break-words text-5xl font-black leading-[.96] tracking-[-.045em] sm:text-6xl md:text-7xl" style={{ fontFamily: spec.theme.headingFont }}>{c.title}</h1><p className="mt-7 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">{c.subtitle}</p><a href={target} className="mt-9 inline-flex rounded-full px-6 py-3.5 text-sm font-black text-slate-950" style={{ background: spec.theme.accent }}>{c.cta || 'Start a conversation'}</a></div><div className="relative min-h-72 overflow-hidden rounded-[2rem] border border-white/10 bg-white/5 p-3 shadow-2xl"><div className="absolute inset-0 opacity-30" style={{ background: `linear-gradient(135deg, ${spec.theme.accent}, transparent 55%)` }} />{image ? <img src={image} alt="" className="relative h-72 w-full rounded-[1.5rem] object-cover opacity-90" /> : <div className="relative grid h-72 place-items-end rounded-[1.5rem] border border-white/10 bg-white/[.03] p-6"><span className="text-right text-3xl font-black tracking-tight text-white/80">Make it<br />memorable.</span></div>}</div></div></Container></Section>;
  if (style === 'premium-minimal') return <Section id="hero" className="bg-[#faf9f6] text-center"><Container className="max-w-4xl"><div className="mx-auto max-w-3xl"><div className="text-[11px] font-bold uppercase tracking-[.3em]" style={{ color: spec.theme.accent }}>{c.eyebrow || 'Established with purpose'}</div><h1 className="mt-7 break-words text-5xl font-medium leading-[1.02] tracking-[-.04em] text-neutral-900 sm:text-6xl md:text-7xl" style={{ fontFamily: 'Georgia, Times New Roman, serif' }}>{c.title}</h1><p className="mx-auto mt-7 max-w-2xl text-base leading-8 text-neutral-600 sm:text-lg">{c.subtitle}</p><a href={target} className="mt-9 inline-flex border-b-2 px-1 py-2 text-sm font-bold text-neutral-900" style={{ borderColor: spec.theme.accent }}>{c.cta || 'Discover more'} <span className="ml-2">↗</span></a></div>{image && <div className="mt-14 overflow-hidden rounded-[1.5rem]"><img src={image} alt="" className="h-64 w-full object-cover sm:h-80 md:h-[26rem]" /></div>}</Container></Section>;
  if (style === 'warm-commerce') return <Section id="hero" className="bg-[#fffaf4]"><Container><div className="grid overflow-hidden rounded-[2rem] bg-[#172018] lg:grid-cols-[.9fr_1.1fr]"><div className="flex flex-col justify-center p-8 text-white sm:p-12 md:p-16"><div className="text-xs font-bold uppercase tracking-[.24em]" style={{ color: spec.theme.accent }}>{c.eyebrow || 'Local, personal, welcoming'}</div><h1 className="mt-5 break-words text-4xl font-black leading-tight sm:text-5xl md:text-6xl">{c.title}</h1><p className="mt-5 max-w-xl leading-7 text-white/70">{c.subtitle}</p><a href={target} className="mt-8 w-fit rounded-full px-6 py-3 text-sm font-black text-white" style={{ background: spec.theme.accent }}>{c.cta || 'Get in touch'}</a></div><div className="min-h-72 bg-white/5">{image ? <img src={image} alt="" className="h-full min-h-72 w-full object-cover" /> : <div className="grid h-full min-h-72 place-items-center p-10 text-center text-2xl font-bold text-white/40">{spec.business.businessName}</div>}</div></div></Container></Section>;
  if (style === 'trusted-community') return <Section id="hero" className="bg-[#f4f8f7] text-center"><Container className="max-w-4xl"><span className="inline-flex rounded-full px-4 py-2 text-xs font-bold" style={{ background: `${spec.theme.accent}18`, color: spec.theme.primary }}>{c.eyebrow || 'Welcome'}</span><h1 className="mt-6 break-words text-4xl font-black leading-tight text-slate-900 sm:text-5xl md:text-6xl">{c.title}</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">{c.subtitle}</p><a href={target} className="mt-8 inline-flex rounded-xl px-6 py-3.5 text-sm font-bold text-white shadow-lg" style={{ background: spec.theme.primary }}>{c.cta || 'Learn more'}</a>{image && <div className="mx-auto mt-12 max-w-3xl overflow-hidden rounded-[2rem]"><img src={image} alt="" className="h-60 w-full object-cover sm:h-80" /></div>}</Container></Section>;
  return <Section id="hero" className="bg-white"><Container><div className="grid items-center gap-12 md:grid-cols-[1.05fr_.95fr]"><div><div className="mb-5 text-xs font-black uppercase tracking-[.22em]" style={{ color: spec.theme.accent }}>{c.eyebrow || 'Modern business'}</div><h1 className="break-words text-5xl font-black leading-[1.02] tracking-tight text-slate-950 md:text-7xl">{c.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{c.subtitle}</p><a href={target} className="mt-8 inline-flex rounded-full px-6 py-3.5 text-sm font-bold text-white shadow-lg" style={{ background: spec.theme.accent }}>{c.cta || 'Get in touch'}</a></div><div className="relative overflow-hidden rounded-[2rem]" style={{ background: `linear-gradient(135deg, ${spec.theme.surface}, ${spec.theme.accent}22)` }}>{image ? <img src={image} alt="" className="h-72 w-full object-cover sm:h-96" /> : <div className="grid min-h-72 place-items-end p-8 sm:min-h-96"><div className="max-w-xs text-right text-4xl font-black leading-tight text-slate-900/70">A clear place for your business to grow.</div></div>}</div></div></Container></Section>;
}

export function About({ spec }: SectionProps) {
  const style = styleOf(spec); const c = (spec.content.about || {}) as { title?: string; body?: string }; const image = heroImage(spec);
  if (style === 'premium-minimal') return <Section id="about" className="bg-white"><Container><div className="grid gap-10 md:grid-cols-[.65fr_1fr] md:items-start"><div><span className="text-[11px] font-bold uppercase tracking-[.3em]" style={{ color: spec.theme.accent }}>01 — About</span></div><div><h2 className="break-words text-4xl font-medium leading-tight text-neutral-900 md:text-5xl" style={{ fontFamily: 'Georgia, Times New Roman, serif' }}>{c.title}</h2><p className="mt-7 max-w-3xl text-lg leading-9 text-neutral-600">{c.body}</p></div></div></Container></Section>;
  if (style === 'trusted-community') return <Section id="about" className="bg-white"><Container><div className="rounded-[2rem] border border-slate-200 p-8 sm:p-12"><span className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: spec.theme.accent }}>About us</span><h2 className="mt-3 break-words text-3xl font-black text-slate-900 md:text-4xl">{c.title}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">{c.body}</p></div></Container></Section>;
  return <Section id="about" className={style === 'creative-bold' ? 'bg-slate-950 text-white' : style === 'warm-commerce' ? 'bg-[#fffaf4]' : 'bg-white'}><Container><div className={`grid gap-10 ${image && style === 'creative-bold' ? 'md:grid-cols-[.75fr_1.25fr]' : ''}`}><div className="max-w-3xl"><p className={`text-xs font-black uppercase tracking-[.2em] ${style === 'creative-bold' ? 'text-cyan-300' : ''}`} style={style === 'creative-bold' ? undefined : { color: spec.theme.accent }}>About</p><h2 className={`mt-3 break-words text-3xl font-black md:text-5xl ${style === 'creative-bold' ? 'text-white' : 'text-slate-950'}`}>{c.title}</h2><p className={`mt-6 text-lg leading-8 ${style === 'creative-bold' ? 'text-slate-300' : 'text-slate-600'}`}>{c.body}</p></div></div></Container></Section>;
}

export function Services({ spec }: SectionProps) {
  const style = styleOf(spec); const list = services(spec);
  if (!list.length) return <Section id="services" className={style === 'creative-bold' ? 'bg-slate-950 text-white' : style === 'warm-commerce' ? 'bg-[#fffaf4]' : 'bg-slate-50'}><Container><Empty title="Services" message="No services have been added yet." dark={style === 'creative-bold'} /></Container></Section>;
  if (style === 'premium-minimal') return <Section id="services" className="bg-[#faf9f6]"><Container><div className="flex items-end justify-between gap-6"><div><span className="text-[11px] font-bold uppercase tracking-[.3em]" style={{ color: spec.theme.accent }}>02 — Services</span><h2 className="mt-3 text-4xl font-medium text-neutral-900 md:text-5xl" style={{ fontFamily: 'Georgia, Times New Roman, serif' }}>What we offer</h2></div></div><div className="mt-10 divide-y divide-neutral-300 border-y border-neutral-300">{list.map((item, i) => <div key={`${item}-${i}`} className="grid gap-4 py-6 sm:grid-cols-[70px_1fr_auto] sm:items-center"><span className="text-xs text-neutral-400">0{i + 1}</span><h3 className="break-words text-xl font-medium text-neutral-900">{item}</h3><span className="text-neutral-400">↗</span></div>)}</div></Container></Section>;
  if (style === 'warm-commerce') return <Section id="services" className="bg-[#fffaf4]"><Container><h2 className="text-3xl font-black text-[#172018] md:text-4xl">Services</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{list.map((item, i) => <article key={`${item}-${i}`} className="rounded-[1.5rem] border border-orange-900/10 bg-white p-6 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-full text-sm font-black text-white" style={{ background: spec.theme.accent }}>{i + 1}</span><h3 className="mt-6 break-words text-lg font-black text-slate-900">{item}</h3></article>)}</div></Container></Section>;
  if (style === 'creative-bold') return <Section id="services" className="bg-slate-950 text-white"><Container><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="text-xs font-black uppercase tracking-[.25em] text-cyan-300">Capabilities</span><h2 className="mt-3 text-4xl font-black md:text-5xl">What we do</h2></div><p className="max-w-md text-sm leading-6 text-slate-400">A focused set of offerings shaped by the business information supplied to this website.</p></div><div className="mt-10 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2">{list.map((item, i) => <article key={`${item}-${i}`} className="min-h-40 bg-slate-950 p-7 transition-transform hover:-translate-y-1"><span className="text-xs text-cyan-300">0{i + 1}</span><h3 className="mt-10 break-words text-xl font-bold">{item}</h3></article>)}</div></Container></Section>;
  if (style === 'trusted-community') return <Section id="services" className="bg-[#f4f8f7]"><Container><h2 className="text-3xl font-black text-slate-900 md:text-4xl">How we help</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{list.map((item, i) => <article key={`${item}-${i}`} className="rounded-2xl bg-white p-7 shadow-sm"><span className="text-sm font-black" style={{ color: spec.theme.accent }}>0{i + 1}</span><h3 className="mt-5 break-words text-lg font-bold text-slate-900">{item}</h3></article>)}</div></Container></Section>;
  return <Section id="services" className="bg-slate-50"><Container><h2 className="text-3xl font-black text-slate-950 md:text-4xl">Services</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{list.map((item, i) => <article key={`${item}-${i}`} className="rounded-3xl border border-black/5 bg-white p-7 shadow-sm"><div className="mb-8 grid h-10 w-10 place-items-center rounded-xl text-sm font-bold text-white" style={{ background: spec.theme.accent }}>0{i + 1}</div><h3 className="break-words text-lg font-bold text-slate-950">{item}</h3></article>)}</div></Container></Section>;
}

export function Products({ spec }: SectionProps) {
  const style = styleOf(spec); const list = products(spec); if (!list.length) return <Section id="products" className={style === 'warm-commerce' ? 'bg-[#fffaf4]' : 'bg-white'}><Container><Empty title="Products" message="No products have been added yet." /></Container></Section>;
  return <Section id="products" className={style === 'warm-commerce' ? 'bg-[#fffaf4]' : 'bg-white'}><Container><div className="flex items-end justify-between gap-5"><div><span className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: spec.theme.accent }}>Collection</span><h2 className="mt-3 text-3xl font-black text-slate-900 md:text-4xl">Products</h2></div></div><div className={`mt-9 grid gap-5 ${style === 'warm-commerce' ? 'sm:grid-cols-2 lg:grid-cols-3' : 'sm:grid-cols-2 md:grid-cols-3'}`}>{list.map((item, i) => <article key={`${item}-${i}`} className={`overflow-hidden ${style === 'warm-commerce' ? 'rounded-[1.5rem] bg-white shadow-sm' : 'rounded-3xl border border-black/5'}`}><div className="grid h-40 place-items-center" style={{ background: `${spec.theme.accent}12` }}><span className="text-5xl font-black opacity-20">{String(i + 1).padStart(2, '0')}</span></div><div className="p-6"><h3 className="break-words font-bold text-slate-900">{item}</h3></div></article>)}</div></Container></Section>;
}

export function Gallery({ spec }: SectionProps) {
  const style = styleOf(spec); const images = gallery(spec); if (!images.length) return <Section id="gallery" className={style === 'creative-bold' ? 'bg-slate-900 text-white' : 'bg-slate-50'}><Container><Empty title="Gallery" message="No gallery images have been added yet." dark={style === 'creative-bold'} /></Container></Section>;
  return <Section id="gallery" className={style === 'creative-bold' ? 'bg-slate-900 text-white' : style === 'premium-minimal' ? 'bg-[#faf9f6]' : 'bg-slate-50'}><Container><h2 className={`text-3xl font-black md:text-4xl ${style === 'creative-bold' ? 'text-white' : 'text-slate-900'}`}>{style === 'premium-minimal' ? 'Selected work' : 'Gallery'}</h2><div className={`mt-9 grid gap-4 ${style === 'creative-bold' ? 'sm:grid-cols-2 lg:grid-cols-12' : 'sm:grid-cols-2 md:grid-cols-3'}`}>{images.map((image, i) => <figure key={`${image}-${i}`} className={`${style === 'creative-bold' && i % 3 === 0 ? 'lg:col-span-7' : style === 'creative-bold' ? 'lg:col-span-5' : ''} overflow-hidden rounded-3xl`}><img src={image} alt="" className={`w-full object-cover ${style === 'creative-bold' && i % 3 === 0 ? 'h-80' : 'h-64'}`} /></figure>)}</div></Container></Section>;
}

export function Testimonials({ spec }: SectionProps) {
  const style = styleOf(spec); const list = testimonials(spec); if (!list.length) return <Section id="testimonials" className={style === 'creative-bold' ? 'bg-slate-950 text-white' : 'bg-white'}><Container><Empty title="Testimonials" message="No testimonials have been added yet." dark={style === 'creative-bold'} /></Container></Section>;
  return <Section id="testimonials" className={style === 'creative-bold' ? 'bg-slate-950 text-white' : style === 'trusted-community' ? 'bg-[#f4f8f7]' : 'bg-white'}><Container><div className="max-w-2xl"><span className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: spec.theme.accent }}>Testimonials</span><h2 className={`mt-3 text-3xl font-black md:text-4xl ${style === 'creative-bold' ? 'text-white' : 'text-slate-900'}`}>Words from customers</h2></div><div className="mt-9 grid gap-5 md:grid-cols-2">{list.map((item, i) => <blockquote key={i} className={`rounded-[1.5rem] p-7 ${style === 'creative-bold' ? 'border border-white/10 bg-white/5' : style === 'premium-minimal' ? 'border-y border-neutral-300' : 'border border-black/5 bg-white shadow-sm'}`}><p className={`text-lg leading-8 ${style === 'creative-bold' ? 'text-slate-200' : 'text-slate-700'}`}>“{item.quote || ''}”</p>{item.author && <footer className="mt-6 text-sm font-bold" style={{ color: spec.theme.accent }}>{item.author}</footer>}</blockquote>)}</div></Container></Section>;
}

export function Pricing({ spec }: SectionProps) {
  const list = pricing(spec); if (!list.length) return <Section id="pricing" className="bg-slate-50"><Container><Empty title="Pricing" message="No pricing plans have been added yet." /></Container></Section>;
  return <Section id="pricing" className="bg-slate-50"><Container><h2 className="text-3xl font-black text-slate-900 md:text-4xl">Pricing</h2><div className="mt-9 grid gap-5 md:grid-cols-3">{list.map((item, i) => <article key={i} className={`rounded-3xl bg-white p-7 shadow-sm ${i === 0 ? 'ring-2 ring-offset-2' : ''}`} style={i === 0 ? { outlineColor: spec.theme.accent } : undefined}><div className="text-xs font-bold uppercase tracking-widest text-slate-400">Option {i + 1}</div><h3 className="mt-4 break-words text-xl font-black text-slate-900">{item.name}</h3><div className="mt-6 text-3xl font-black" style={{ color: spec.theme.accent }}>{item.price}</div></article>)}</div></Container></Section>;
}

export function FAQ({ spec }: SectionProps) {
  const list = faqs(spec); if (!list.length) return <Section id="faq"><Container><Empty title="FAQ" message="No frequently asked questions have been added yet." /></Container></Section>;
  return <Section id="faq"><Container className="max-w-4xl"><div className="text-center"><span className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: spec.theme.accent }}>Questions</span><h2 className="mt-3 text-3xl font-black text-slate-900 md:text-4xl">Frequently asked</h2></div><div className="mt-9 space-y-3">{list.map((item, i) => <details key={i} className="group rounded-2xl border border-black/5 bg-white p-5 shadow-sm"><summary className="cursor-pointer list-none pr-8 font-bold text-slate-900 marker:hidden">{item.question}<span className="float-right transition-transform group-open:rotate-45">+</span></summary>{item.answer && <p className="mt-4 max-w-3xl leading-7 text-slate-600">{item.answer}</p>}</details>)}</div></Container></Section>;
}

export function Contact({ spec }: SectionProps) {
  const style = styleOf(spec); const c = (spec.content.contact || {}) as { phone?: string; email?: string; whatsapp?: string }; const values = [{ label: 'Phone', value: c.phone }, { label: 'Email', value: c.email }, { label: 'WhatsApp', value: c.whatsapp }].filter((item) => item.value?.trim());
  return <Section id="contact" className={style === 'premium-minimal' ? 'bg-[#171717] text-white' : style === 'trusted-community' ? 'bg-[#17324d] text-white' : 'text-white'} style={style !== 'premium-minimal' && style !== 'trusted-community' ? { background: spec.theme.primary } : undefined}><Container><div className="grid gap-10 md:grid-cols-[1fr_auto] md:items-end"><div><span className="text-xs font-bold uppercase tracking-[.22em]" style={{ color: style === 'premium-minimal' ? spec.theme.accent : '#fff' }}>Contact</span><h2 className="mt-4 break-words text-4xl font-black md:text-6xl">Let’s connect.</h2><p className="mt-5 max-w-xl leading-7 text-white/70">Reach the business using the contact details provided for this website.</p></div><div className="flex flex-col gap-3">{values.length ? values.map((item) => <span key={`${item.label}-${item.value}`} className="rounded-full border border-white/15 bg-white/10 px-5 py-3 text-sm font-semibold">{item.label}: {item.value}</span>) : <span className="rounded-full border border-white/15 bg-white/10 px-5 py-3 text-sm text-white/70">Contact details not added yet.</span>}</div></div></Container></Section>;
}

export function Location({ spec }: SectionProps) {
  const c = (spec.content.location || {}) as { address?: string }; if (!c.address?.trim()) return null; const style = styleOf(spec);
  return <Section id="location" className={style === 'warm-commerce' ? 'bg-[#fffaf4]' : style === 'trusted-community' ? 'bg-[#f4f8f7]' : 'bg-white'}><Container><div className="flex flex-col gap-5 rounded-3xl border border-black/5 p-7 sm:p-10 md:flex-row md:items-center md:justify-between"><div><span className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: spec.theme.accent }}>Location</span><h2 className="mt-3 text-2xl font-black text-slate-900">Visit us</h2></div><p className="max-w-xl break-words text-slate-600">{c.address}</p></div></Container></Section>;
}

export function Footer({ spec }: SectionProps) {
  const style = styleOf(spec); const dark = style === 'creative-bold' || style === 'premium-minimal'; return <footer id="footer" className={`border-t px-5 py-10 sm:px-8 ${dark ? 'border-white/10 bg-slate-950 text-slate-300' : 'border-black/5 bg-white text-slate-500'}`}><Container><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><Brand spec={spec} light={dark} /><div className="text-sm">© {new Date().getFullYear()} {spec.business.businessName}</div>{spec.attribution.enabled && <div className="text-xs opacity-70">{spec.attribution.label}</div>}</div></Container></footer>;
}

function Empty({ title, message, dark = false }: { title: string; message: string; dark?: boolean }) { return <div><h2 className={`text-3xl font-black ${dark ? 'text-white' : 'text-slate-900'}`}>{title}</h2><p className={`mt-4 text-sm ${dark ? 'text-slate-400' : 'text-slate-500'}`}>{message}</p></div>; }
