import type { CSSProperties, ReactNode } from 'react';
import type { WebsiteSectionId, WebsiteSpecification } from '../../lib/websiteCreation/types';
import { getWebsiteTemplatePresentation } from '../../lib/websiteCreation/presentation';

interface SectionProps { spec: WebsiteSpecification; }
type StyleKey = ReturnType<typeof getWebsiteTemplatePresentation>['styleKey'];
type Item = Record<string, any>;

const Section = ({ id, children, className = '', style }: { id: string; children: ReactNode; className?: string; style?: CSSProperties }) => <section id={id} className={`px-5 py-16 sm:px-8 md:px-10 md:py-24 ${className}`} style={style}>{children}</section>;
const Container = ({ children, className = '' }: { children: ReactNode; className?: string }) => <div className={`mx-auto w-full max-w-6xl ${className}`}>{children}</div>;
const styleOf = (spec: WebsiteSpecification): StyleKey => getWebsiteTemplatePresentation(spec).styleKey;
const data = (spec: WebsiteSpecification, section: WebsiteSectionId) => (spec.content[section] || {}) as Item;
const array = (spec: WebsiteSpecification, section: WebsiteSectionId) => Array.isArray(data(spec, section).items) ? data(spec, section).items as Item[] : [];
const textItems = (spec: WebsiteSpecification, section: WebsiteSectionId) => array(spec, section).map((item) => typeof item === 'string' ? { name: item, title: item } : item).filter((item) => item.name || item.title || item.description || item.body);
const imageList = (spec: WebsiteSpecification, section: WebsiteSectionId) => Array.isArray(data(spec, section).images) ? data(spec, section).images.map(String).filter(Boolean) : [];
const heroImage = (spec: WebsiteSpecification) => spec.business.imagery?.find(Boolean) || '';
const safeImage = (spec: WebsiteSpecification, index = 0) => spec.business.imagery?.filter(Boolean)?.[index] || '';
const initials = (name: string) => name.trim().split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase() || 'A';

function Brand({ spec, light = false }: { spec: WebsiteSpecification; light?: boolean }) { return <div className="flex min-w-0 items-center gap-3 font-semibold" style={{ color: light ? '#fff' : spec.theme.primary }}>{spec.business.logoUrl ? <img src={spec.business.logoUrl} alt="" className="h-10 w-10 shrink-0 rounded-xl object-cover" /> : <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl text-xs font-black" style={{ background: spec.theme.accent, color: '#fff' }}>{initials(spec.business.businessName)}</span>}<span className="min-w-0 break-words text-sm sm:text-base">{spec.business.businessName}</span></div>; }

export function Navbar({ spec }: SectionProps) { const style = styleOf(spec); const links = spec.navigation.filter((item) => !['navbar','hero','footer'].includes(item.section)).slice(0, 6); const dark = style === 'creative-bold'; return <header className={`sticky top-0 z-30 border-b px-5 py-4 backdrop-blur-xl sm:px-8 ${dark ? 'border-white/10 bg-slate-950/90' : 'border-black/5 bg-white/90'}`}><Container><div className="flex items-center justify-between gap-5"><Brand spec={spec} light={dark}/><nav className={`hidden flex-wrap justify-end gap-5 text-sm md:flex ${dark ? 'text-slate-200' : 'text-slate-600'}`}>{links.map((item) => <a key={item.section} href={`#${item.section}`} className="transition-opacity hover:opacity-60">{item.label}</a>)}</nav><details className="relative md:hidden"><summary className={`cursor-pointer list-none rounded-full border px-4 py-2 text-xs font-bold ${dark ? 'border-white/15 text-white' : 'border-black/10 text-slate-700'}`}>Menu</summary><div className={`absolute right-0 mt-3 w-56 rounded-2xl border p-3 shadow-2xl ${dark ? 'border-white/10 bg-slate-900' : 'border-black/5 bg-white'}`}>{links.map((item) => <a key={item.section} href={`#${item.section}`} className={`block rounded-xl px-3 py-2.5 text-sm ${dark ? 'text-slate-200 hover:bg-white/5' : 'text-slate-700 hover:bg-slate-50'}`}>{item.label}</a>)}</div></details></div></Container></header>; }

export function Hero({ spec }: SectionProps) { const style = styleOf(spec); const c = data(spec,'hero'); const image = heroImage(spec); const target = spec.sections.includes('contact') ? '#contact' : '#footer'; if (style === 'creative-bold') return <Section id="hero" className="relative overflow-hidden bg-slate-950 text-white" style={{ background: `radial-gradient(circle at 75% 15%, ${spec.theme.accent}35, transparent 32%), linear-gradient(135deg, ${spec.theme.primary}, #050816)` }}><Container><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div className="pt-8 md:pt-16"><p className="text-xs font-black uppercase tracking-[.3em] text-cyan-300">{c.eyebrow || 'Creative studio'}</p><h1 className="mt-6 max-w-5xl break-words text-5xl font-black leading-[.92] tracking-[-.055em] sm:text-7xl lg:text-8xl">{c.title}</h1><p className="mt-8 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">{c.subtitle}</p><a href={target} className="mt-9 inline-flex rounded-full px-6 py-3.5 text-sm font-black text-slate-950 transition-transform hover:-translate-y-1" style={{ background: spec.theme.accent }}>{c.cta || 'Start a project'} ↗</a></div><div className="relative overflow-hidden rounded-[2.5rem] border border-white/10 bg-white/5 p-3"><div className="absolute inset-0" style={{ background: `linear-gradient(145deg, ${spec.theme.accent}44, transparent 55%)` }}/>{image ? <img src={image} alt={`${spec.business.businessName} visual`} className="relative h-80 w-full rounded-[2rem] object-cover opacity-90 sm:h-[30rem]"/> : <div className="grid h-80 place-items-end rounded-[2rem] border border-white/10 p-8 sm:h-[30rem]"><span className="max-w-xs text-right text-4xl font-black">Make it impossible to ignore.</span></div>}</div></div></Container></Section>;
  if (style === 'premium-minimal') return <Section id="hero" className="bg-[#f7f5f0] text-center"><Container className="max-w-5xl"><p className="text-[11px] font-bold uppercase tracking-[.32em]" style={{color:spec.theme.accent}}>{c.eyebrow || 'A considered approach'}</p><h1 className="mx-auto mt-7 max-w-4xl break-words text-5xl font-medium leading-[.98] tracking-[-.055em] text-neutral-900 sm:text-7xl">{c.title}</h1><p className="mx-auto mt-7 max-w-2xl text-base leading-8 text-neutral-600 sm:text-lg">{c.subtitle}</p><a href={target} className="mt-9 inline-flex border-b-2 px-1 py-2 text-sm font-bold text-neutral-900" style={{borderColor:spec.theme.accent}}>{c.cta || 'Discover more'} ↗</a>{image && <img src={image} alt={`${spec.business.businessName} visual`} className="mt-16 h-72 w-full rounded-[2rem] object-cover sm:h-[28rem]"/>}</Container></Section>;
  if (style === 'warm-commerce') return <Section id="hero" className="bg-[#fff8ef]"><Container><div className="grid overflow-hidden rounded-[2.5rem] bg-[#18301f] lg:grid-cols-[.9fr_1.1fr]"><div className="flex flex-col justify-center p-8 text-white sm:p-12 md:p-16"><p className="text-xs font-bold uppercase tracking-[.24em]" style={{color:spec.theme.accent}}>{c.eyebrow || 'Local, personal, welcoming'}</p><h1 className="mt-5 break-words text-4xl font-black leading-[1.02] sm:text-6xl">{c.title}</h1><p className="mt-5 max-w-xl leading-7 text-white/70">{c.subtitle}</p><a href={target} className="mt-8 w-fit rounded-full px-6 py-3.5 text-sm font-black text-white" style={{background:spec.theme.accent}}>{c.cta || 'Visit us'} ↗</a></div><div className="min-h-72 bg-white/5">{image ? <img src={image} alt={`${spec.business.businessName} visual`} className="h-full min-h-72 w-full object-cover lg:min-h-[34rem]"/> : <div className="grid min-h-72 place-items-center p-10 text-center text-3xl font-black text-white/40 lg:min-h-[34rem]">{spec.business.businessName}</div>}</div></div></Container></Section>;
  if (style === 'trusted-community') return <Section id="hero" className="bg-[#edf5f2] text-center"><Container className="max-w-5xl"><span className="inline-flex rounded-full px-4 py-2 text-xs font-bold" style={{background:`${spec.theme.accent}18`,color:spec.theme.primary}}>{c.eyebrow || 'Welcome'}</span><h1 className="mx-auto mt-6 max-w-4xl break-words text-4xl font-black leading-tight text-slate-900 sm:text-6xl">{c.title}</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">{c.subtitle}</p><a href={target} className="mt-8 inline-flex rounded-xl px-6 py-3.5 text-sm font-bold text-white shadow-lg transition-transform hover:-translate-y-0.5" style={{background:spec.theme.primary}}>{c.cta || 'Learn more'} ↗</a>{image && <img src={image} alt={`${spec.business.businessName} visual`} className="mx-auto mt-12 h-64 w-full max-w-4xl rounded-[2rem] object-cover sm:h-96"/>}</Container></Section>;
  return <Section id="hero" className="bg-white"><Container><div className="grid items-center gap-12 md:grid-cols-[1.05fr_.95fr]"><div><p className="text-xs font-black uppercase tracking-[.24em]" style={{color:spec.theme.accent}}>{c.eyebrow || 'Modern business'}</p><h1 className="mt-5 break-words text-5xl font-black leading-[.98] tracking-[-.05em] text-slate-950 md:text-7xl">{c.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{c.subtitle}</p><a href={target} className="mt-8 inline-flex rounded-full px-6 py-3.5 text-sm font-bold text-white shadow-lg transition-transform hover:-translate-y-0.5" style={{background:spec.theme.accent}}>{c.cta || 'Get in touch'} ↗</a></div><div className="overflow-hidden rounded-[2.5rem]" style={{background:`linear-gradient(135deg,${spec.theme.surface},${spec.theme.accent}22)`}}>{image ? <img src={image} alt={`${spec.business.businessName} visual`} className="h-80 w-full object-cover sm:h-[30rem]"/> : <div className="grid h-80 place-items-end p-8 sm:h-[30rem]"><span className="max-w-sm text-right text-4xl font-black text-slate-900/70">A clearer way forward.</span></div>}</div></div></Container></Section>; }

export function About({ spec }: SectionProps) { const style=styleOf(spec); const c=data(spec,'about'); return <Section id="about" className={style==='creative-bold'?'bg-slate-950 text-white':style==='warm-commerce'?'bg-[#fff8ef]':'bg-white'}><Container><div className="grid gap-10 md:grid-cols-[.35fr_1fr]"><div><p className={`text-xs font-black uppercase tracking-[.24em] ${style==='creative-bold'?'text-cyan-300':''}`} style={style==='creative-bold'?undefined:{color:spec.theme.accent}}>{c.kicker || 'About'}</p></div><div className="max-w-4xl"><h2 className={`break-words text-4xl font-black leading-tight md:text-6xl ${style==='creative-bold'?'text-white':'text-slate-950'}`}>{c.title || `About ${spec.business.businessName}`}</h2><p className={`mt-7 text-lg leading-9 ${style==='creative-bold'?'text-slate-300':'text-slate-600'}`}>{c.body || spec.business.businessDescription}</p></div></div></Container></Section>; }

export function Stats({ spec }: SectionProps) { const style=styleOf(spec); const items=array(spec,'stats'); if(!items.length)return null; return <Section id="stats" className={style==='creative-bold'?'bg-slate-900 text-white':style==='warm-commerce'?'bg-[#18301f] text-white':'bg-slate-950 text-white'}><Container><div className="grid gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 md:grid-cols-3">{items.map((item,i)=><article key={i} className="bg-white/[.03] p-7 sm:p-9"><div className="text-4xl font-black tracking-tight" style={{color:style==='creative-bold'?spec.theme.accent:'#fff'}}>{item.value}</div><h3 className="mt-4 text-sm font-bold">{item.label}</h3>{item.detail&&<p className="mt-2 text-sm leading-6 text-white/55">{item.detail}</p>}</article>)}</div></Container></Section>; }

export function Story({ spec }: SectionProps) { const c=data(spec,'story'); const image=c.image || heroImage(spec); if(!c.title&&!c.body)return null; return <Section id="story" className="bg-[#f7f5f0]"><Container><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr] md:items-center"><div>{image&&<img src={image} alt={`${spec.business.businessName} story`} className="h-80 w-full rounded-[2rem] object-cover md:h-[30rem]"/>}</div><div><p className="text-[11px] font-bold uppercase tracking-[.3em]" style={{color:spec.theme.accent}}>{c.kicker || 'The story'}</p><h2 className="mt-4 break-words text-4xl font-medium leading-tight text-neutral-900 md:text-6xl">{c.title}</h2><p className="mt-7 text-lg leading-9 text-neutral-600">{c.body}</p>{c.quote&&<blockquote className="mt-8 border-l-2 pl-6 text-xl italic text-neutral-800" style={{borderColor:spec.theme.accent}}>{c.quote}</blockquote>}</div></div></Container></Section>; }

export function Values({ spec }: SectionProps) { const items=array(spec,'values'); if(!items.length)return null; return <Section id="values" className="bg-white"><Container><div className="max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[.3em]" style={{color:spec.theme.accent}}>Values</p><h2 className="mt-4 text-4xl font-medium text-neutral-900 md:text-5xl">What guides the work.</h2></div><div className="mt-12 grid gap-0 border-y border-neutral-300 md:grid-cols-3">{items.map((item,i)=><article key={i} className="border-b border-neutral-300 p-7 md:border-b-0 md:border-r last:border-r-0"><span className="text-xs text-neutral-400">0{i+1}</span><h3 className="mt-10 text-xl font-semibold text-neutral-900">{item.title}</h3><p className="mt-4 leading-7 text-neutral-600">{item.body}</p></article>)}</div></Container></Section>; }

export function Process({ spec }: SectionProps) { const style=styleOf(spec); const items=array(spec,'process'); if(!items.length)return null; return <Section id="process" className={style==='creative-bold'?'bg-slate-950 text-white':'bg-slate-50'}><Container><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>Process</p><h2 className={`mt-3 text-4xl font-black md:text-5xl ${style==='creative-bold'?'text-white':'text-slate-950'}`}>Simple by design.</h2></div><p className={`max-w-md text-sm leading-6 ${style==='creative-bold'?'text-slate-400':'text-slate-500'}`}>A clear sequence keeps decisions moving and makes progress visible.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{items.map((item,i)=><article key={i} className={`rounded-[1.75rem] p-7 ${style==='creative-bold'?'border border-white/10 bg-white/[.04]':'border border-black/5 bg-white shadow-sm'}`}><span className="text-xs font-black" style={{color:spec.theme.accent}}>{item.step || `0${i+1}`}</span><h3 className={`mt-10 text-xl font-bold ${style==='creative-bold'?'text-white':'text-slate-950'}`}>{item.title}</h3><p className={`mt-4 leading-7 ${style==='creative-bold'?'text-slate-400':'text-slate-600'}`}>{item.body}</p></article>)}</div></Container></Section>; }

export function Services({ spec }: SectionProps) { const style=styleOf(spec); const items=textItems(spec,'services'); if(!items.length)return null; return <Section id="services" className={style==='creative-bold'?'bg-slate-950 text-white':style==='premium-minimal'?'bg-[#f7f5f0]':style==='warm-commerce'?'bg-[#fff8ef]':style==='trusted-community'?'bg-[#edf5f2]':'bg-slate-50'}><Container><div className="flex items-end justify-between gap-6"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>Services</p><h2 className={`mt-3 text-4xl font-black md:text-5xl ${style==='creative-bold'?'text-white':'text-slate-950'}`}>{style==='premium-minimal'?'What we offer':'Capabilities'}</h2></div></div>{style==='premium-minimal'?<div className="mt-10 divide-y divide-neutral-300 border-y border-neutral-300">{items.map((item,i)=><div key={i} className="grid gap-4 py-7 sm:grid-cols-[70px_1fr_auto]"><span className="text-xs text-neutral-400">0{i+1}</span><h3 className="text-xl font-medium text-neutral-900">{item.name || item.title}</h3><span className="text-neutral-400">↗</span></div>)}</div>:<div className="mt-10 grid gap-4 md:grid-cols-3">{items.map((item,i)=><article key={i} className={`rounded-[1.75rem] p-7 transition-transform hover:-translate-y-1 ${style==='creative-bold'?'border border-white/10 bg-white/[.04]':'bg-white shadow-sm border border-black/5'}`}><span className="grid h-10 w-10 place-items-center rounded-xl text-xs font-black text-white" style={{background:spec.theme.accent}}>0{i+1}</span><h3 className={`mt-8 text-xl font-bold ${style==='creative-bold'?'text-white':'text-slate-950'}`}>{item.name || item.title}</h3>{item.description&&<p className={`mt-3 text-sm leading-6 ${style==='creative-bold'?'text-slate-400':'text-slate-600'}`}>{item.description}</p>}</article>)}</div>}</Container></Section>; }

export function Offers({ spec }: SectionProps) { const style=styleOf(spec); const items=array(spec,'offers'); if(!items.length)return null; return <Section id="offers" className="bg-[#fff8ef]"><Container><div className="flex items-end justify-between gap-6"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>Offers</p><h2 className="mt-3 text-4xl font-black text-[#18301f] md:text-5xl">Good things, right now.</h2></div></div><div className="mt-10 grid gap-5 md:grid-cols-2">{items.map((item,i)=><article key={i} className={`rounded-[2rem] p-7 ${item.featured?'bg-[#18301f] text-white shadow-xl':'border border-orange-900/10 bg-white text-slate-900 shadow-sm'}`}><div className="text-xs font-bold uppercase tracking-[.2em] opacity-60">{item.label}</div><h3 className="mt-4 text-2xl font-black">{item.title}</h3><p className="mt-3 max-w-xl leading-7 opacity-70">{item.description}</p><div className="mt-7 text-lg font-black" style={{color:item.featured?spec.theme.accent:spec.theme.primary}}>{item.price}</div></article>)}</div></Container></Section>; }

export function Products({ spec }: SectionProps) { const style=styleOf(spec); const items=array(spec,'products').map((item)=>typeof item==='string'?{name:item}:item); if(!items.length)return null; return <Section id="products" className="bg-[#fff8ef]"><Container><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>Collection</p><h2 className="mt-3 text-4xl font-black text-[#18301f] md:text-5xl">Made for everyday.</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map((item,i)=><article key={i} className="overflow-hidden rounded-[1.75rem] bg-white shadow-sm"><div className="h-52 overflow-hidden" style={{background:`${spec.theme.accent}14`}}>{item.image?<img src={item.image} alt={item.name||'Product'} className="h-full w-full object-cover transition-transform duration-500 hover:scale-105"/>:<div className="grid h-full place-items-center text-6xl font-black text-black/10">{String(i+1).padStart(2,'0')}</div>}</div><div className="p-6"><h3 className="text-lg font-black text-slate-900">{item.name || item.title}</h3>{item.detail&&<p className="mt-2 text-sm leading-6 text-slate-500">{item.detail}</p>}{item.price&&<div className="mt-5 font-black" style={{color:spec.theme.primary}}>{item.price}</div>}</div></article>)}</div></Container></Section>; }

export function Gallery({ spec }: SectionProps) { const style=styleOf(spec); const images=imageList(spec,'gallery'); if(!images.length)return null; return <Section id="gallery" className={style==='creative-bold'?'bg-slate-900 text-white':style==='premium-minimal'?'bg-[#f7f5f0]':'bg-white'}><Container><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>{style==='premium-minimal'?'Editorial':'Gallery'}</p><h2 className={`mt-3 text-4xl font-black md:text-5xl ${style==='creative-bold'?'text-white':'text-slate-950'}`}>{style==='premium-minimal'?'Selected details':'A visual chapter'}</h2></div></div><div className={`mt-10 grid gap-4 ${style==='creative-bold'?'md:grid-cols-12':'md:grid-cols-3'}`}>{images.map((image,i)=><figure key={`${image}-${i}`} className={`overflow-hidden rounded-[1.75rem] ${style==='creative-bold'?(i%3===0?'md:col-span-7':'md:col-span-5'):''}`}><img src={image} alt={`${spec.business.businessName} gallery ${i+1}`} className={`w-full object-cover transition-transform duration-700 hover:scale-105 ${style==='creative-bold'&&i%3===0?'h-[28rem]':'h-72'}`}/></figure>)}</div></Container></Section>; }

export function Portfolio({ spec }: SectionProps) { const style=styleOf(spec); const items=array(spec,'portfolio'); if(!items.length)return null; return <Section id="portfolio" className={style==='creative-bold'?'bg-slate-950 text-white':'bg-white'}><Container><div className="flex items-end justify-between gap-6"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>Selected work</p><h2 className={`mt-3 text-4xl font-black md:text-6xl ${style==='creative-bold'?'text-white':'text-slate-950'}`}>Projects with a point of view.</h2></div></div><div className="mt-12 space-y-5">{items.map((item,i)=><article key={i} className={`group grid overflow-hidden rounded-[2rem] border ${style==='creative-bold'?'border-white/10 bg-white/[.03]':'border-black/5 bg-slate-50'} md:grid-cols-[.9fr_1.1fr]`}><div className="min-h-64 overflow-hidden">{item.image?<img src={item.image} alt={item.title||'Project'} className="h-full min-h-64 w-full object-cover transition-transform duration-700 group-hover:scale-105"/>:<div className="grid h-full min-h-64 place-items-center" style={{background:`linear-gradient(135deg,${spec.theme.primary},${spec.theme.accent})`}}><span className="text-7xl font-black text-white/20">0{i+1}</span></div>}</div><div className="flex flex-col justify-between p-7 sm:p-10"><div><p className="text-xs font-bold uppercase tracking-[.2em]" style={{color:spec.theme.accent}}>{item.category}</p><h3 className={`mt-4 text-3xl font-black ${style==='creative-bold'?'text-white':'text-slate-950'}`}>{item.title}</h3><p className={`mt-4 max-w-xl leading-7 ${style==='creative-bold'?'text-slate-400':'text-slate-600'}`}>{item.description}</p></div>{item.result&&<div className="mt-8 border-t border-current/10 pt-5 text-sm font-bold">{item.result}</div>}</div></article>)}</div></Container></Section>; }

export function Team({ spec }: SectionProps) { const items=array(spec,'team'); if(!items.length)return null; return <Section id="team" className="bg-slate-50"><Container><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>People</p><h2 className="mt-3 text-4xl font-black text-slate-950 md:text-5xl">A team built to move with you.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{items.map((item,i)=><article key={i} className="rounded-[1.75rem] border border-black/5 bg-white p-6 shadow-sm"><div className="grid h-24 w-24 place-items-center overflow-hidden rounded-2xl" style={{background:`${spec.theme.accent}18`}}>{item.image?<img src={item.image} alt={item.name||'Team member'} className="h-full w-full object-cover"/>:<span className="text-xl font-black" style={{color:spec.theme.primary}}>{initials(item.name||'Team')}</span>}</div><h3 className="mt-6 text-lg font-black text-slate-950">{item.name}</h3><p className="mt-1 text-sm font-semibold" style={{color:spec.theme.accent}}>{item.role}</p>{item.bio&&<p className="mt-4 text-sm leading-6 text-slate-600">{item.bio}</p>}</article>)}</div></Container></Section>; }

export function Testimonials({ spec }: SectionProps) { const style=styleOf(spec); const items=array(spec,'testimonials'); if(!items.length)return null; return <Section id="testimonials" className={style==='creative-bold'?'bg-slate-950 text-white':style==='trusted-community'?'bg-[#edf5f2]':'bg-white'}><Container><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>Testimonials</p><h2 className={`mt-3 text-4xl font-black md:text-5xl ${style==='creative-bold'?'text-white':'text-slate-950'}`}>People remember how you made them feel.</h2><div className="mt-10 grid gap-5 md:grid-cols-2">{items.map((item,i)=><blockquote key={i} className={`rounded-[1.75rem] p-8 ${style==='creative-bold'?'border border-white/10 bg-white/[.04]':'border border-black/5 bg-slate-50'}`}><div className="text-3xl" style={{color:spec.theme.accent}}>“</div><p className={`mt-3 text-xl leading-8 ${style==='creative-bold'?'text-slate-200':'text-slate-700'}`}>{item.quote}</p>{item.author&&<footer className="mt-7 text-sm font-bold" style={{color:spec.theme.accent}}>{item.author}</footer>}</blockquote>)}</div></Container></Section>; }

export function Pricing({ spec }: SectionProps) { const items=array(spec,'pricing'); if(!items.length)return null; return <Section id="pricing" className="bg-slate-50"><Container><h2 className="text-4xl font-black text-slate-950">Plans that stay clear.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{items.map((item,i)=><article key={i} className="rounded-[1.75rem] bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Option {i+1}</p><h3 className="mt-4 text-xl font-black">{item.name}</h3><div className="mt-7 text-3xl font-black" style={{color:spec.theme.accent}}>{item.price}</div>{item.description&&<p className="mt-4 text-sm leading-6 text-slate-600">{item.description}</p>}</article>)}</div></Container></Section>; }

export function FAQ({ spec }: SectionProps) { const style=styleOf(spec); const items=array(spec,'faq'); if(!items.length)return null; return <Section id="faq" className={style==='trusted-community'?'bg-white':'bg-slate-50'}><Container className="max-w-4xl"><p className="text-center text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>Questions</p><h2 className="mt-3 text-center text-4xl font-black text-slate-950 md:text-5xl">Useful answers, without the runaround.</h2><div className="mt-10 space-y-3">{items.map((item,i)=><details key={i} className="group rounded-2xl border border-black/5 bg-white p-5 shadow-sm"><summary className="cursor-pointer list-none pr-8 font-bold text-slate-900">{item.question}<span className="float-right transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 leading-7 text-slate-600">{item.answer}</p></details>)}</div></Container></Section>; }

export function Hours({ spec }: SectionProps) { const items=array(spec,'hours'); if(!items.length)return null; return <Section id="hours" className="bg-[#fff8ef]"><Container><div className="grid gap-10 md:grid-cols-[.7fr_1.3fr] md:items-start"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>Opening hours</p><h2 className="mt-3 text-4xl font-black text-[#18301f]">Come by when it suits you.</h2></div><div className="divide-y divide-orange-900/10 border-y border-orange-900/10">{items.map((item,i)=><div key={i} className="flex justify-between gap-5 py-5 text-sm"><span className="font-semibold text-slate-800">{item.day}</span><span className="text-slate-500">{item.hours || (item.closed?'Closed':'')}</span></div>)}</div></div></Container></Section>; }

export function Location({ spec }: SectionProps) { const c=data(spec,'location'); if(!c.address)return null; const style=styleOf(spec); return <Section id="location" className={style==='warm-commerce'?'bg-[#fff8ef]':style==='trusted-community'?'bg-[#edf5f2]':'bg-white'}><Container><div className="grid gap-8 rounded-[2rem] border border-black/5 p-7 sm:p-10 md:grid-cols-[.7fr_1.3fr] md:items-center"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>Location</p><h2 className="mt-3 text-3xl font-black text-slate-950">Find us here.</h2></div><p className="break-words text-lg leading-8 text-slate-600">{c.address}</p></div></Container></Section>; }

export function Social({ spec }: SectionProps) { const items=array(spec,'social'); if(!items.length)return null; return <Section id="social" className="bg-white"><Container><div className="flex flex-wrap gap-3">{items.map((item,i)=><a key={i} href={item.url} target="_blank" rel="noreferrer" className="rounded-full border border-black/10 px-5 py-3 text-sm font-semibold text-slate-700 transition hover:-translate-y-0.5 hover:border-black/20">{item.label} ↗</a>)}</div></Container></Section>; }

export function FinalCta({ spec }: SectionProps) { const style=styleOf(spec); const c=data(spec,'finalCta'); if(!c.title)return null; return <Section id="finalCta" className={style==='creative-bold'?'bg-slate-950 text-white':style==='warm-commerce'?'bg-[#18301f] text-white':style==='trusted-community'?'bg-[#17324d] text-white':'bg-slate-900 text-white'}><Container><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>Next step</p><h2 className="mt-4 break-words text-4xl font-black leading-tight md:text-6xl">{c.title}</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/65">{c.body}</p></div><a href={spec.sections.includes('contact')?'#contact':'#footer'} className="w-fit rounded-full px-6 py-3.5 text-sm font-black text-slate-950" style={{background:spec.theme.accent}}>{c.cta || 'Get started'} ↗</a></div></Container></Section>; }

export function Contact({ spec }: SectionProps) { const style=styleOf(spec); const c=data(spec,'contact'); const values=[['Phone',c.phone],['Email',c.email],['WhatsApp',c.whatsapp]].filter(([,v])=>String(v||'').trim()); return <Section id="contact" className={style==='premium-minimal'?'bg-[#171717] text-white':style==='trusted-community'?'bg-[#17324d] text-white':'text-white'} style={style!=='premium-minimal'&&style!=='trusted-community'?{background:spec.theme.primary}:undefined}><Container><div className="grid gap-10 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:spec.theme.accent}}>Contact</p><h2 className="mt-4 text-4xl font-black md:text-6xl">Let’s make the next step simple.</h2><p className="mt-5 max-w-xl leading-7 text-white/65">Reach {spec.business.businessName} using the details below.</p></div><div className="flex flex-col gap-3">{values.length?values.map(([label,value])=><span key={`${label}-${value}`} className="rounded-full border border-white/15 bg-white/10 px-5 py-3 text-sm font-semibold">{label}: {value}</span>):<span className="rounded-full border border-white/15 bg-white/10 px-5 py-3 text-sm text-white/60">Contact details will appear here.</span>}</div></div></Container></Section>; }

export function Footer({ spec }: SectionProps) { const style=styleOf(spec); const dark=style==='creative-bold'||style==='premium-minimal'; return <footer id="footer" className={`border-t px-5 py-10 sm:px-8 ${dark?'border-white/10 bg-slate-950 text-slate-300':'border-black/5 bg-white text-slate-500'}`}><Container><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><Brand spec={spec} light={dark}/><div className="text-sm">© {new Date().getFullYear()} {spec.business.businessName}</div>{spec.attribution.enabled&&<div className="text-xs opacity-70">{spec.attribution.label}</div>}</div></Container></footer>; }
