import type { CSSProperties, ReactNode } from 'react';
import type { WebsiteSpecification } from '../../lib/websiteCreation/types';

interface SectionProps { spec: WebsiteSpecification; }
const Section = ({ id, children, className = '', style }: { id: string; children: ReactNode; className?: string; style?: CSSProperties }) => <section id={id} className={`px-6 py-16 md:px-10 md:py-24 ${className}`} style={style}>{children}</section>;
const Container = ({ children }: { children: ReactNode }) => <div className="mx-auto w-full max-w-6xl">{children}</div>;

export function Navbar({ spec }: SectionProps) {
  return <header className="sticky top-0 z-10 border-b border-black/5 bg-white/85 px-6 py-4 backdrop-blur-md"><Container><div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3 font-semibold" style={{ color: spec.theme.primary }}>{spec.business.logoUrl ? <img src={spec.business.logoUrl} alt="" className="h-9 w-9 shrink-0 rounded-lg object-cover" /> : <span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg" style={{ background: spec.theme.accent, color: '#fff' }}>{spec.business.businessName.charAt(0)}</span>}<span className="min-w-0 break-words">{spec.business.businessName}</span></div><nav className="flex min-w-0 flex-wrap gap-x-3 gap-y-1 text-xs text-slate-600 sm:justify-end sm:gap-x-5 sm:text-sm">{spec.navigation.slice(0, 6).map((item) => <a key={item.section} href={`#${item.section}`} className="break-words hover:text-slate-950">{item.label}</a>)}</nav></div></Container></header>;
}

export function Hero({ spec }: SectionProps) { const c = spec.content.hero as { eyebrow?: string; title?: string; subtitle?: string; cta?: string }; const ctaTarget = spec.sections.includes('contact') ? '#contact' : spec.sections.includes('footer') ? '#footer' : spec.navigation[0] ? `#${spec.navigation[0].section}` : '#hero'; return <Section id="hero" className="overflow-hidden" style={{ background: `linear-gradient(135deg, ${spec.theme.surface}, #fff)` }}><Container><div className="grid items-center gap-12 md:grid-cols-[1.15fr_.85fr]"><div><div className="mb-5 text-xs font-bold uppercase tracking-[.22em]" style={{ color: spec.theme.accent }}>{c.eyebrow || 'Welcome'}</div><h1 className="text-4xl font-black tracking-tight text-slate-950 md:text-6xl" style={{ fontFamily: spec.theme.headingFont }}>{c.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{c.subtitle}</p><a href={ctaTarget} className="mt-8 inline-flex rounded-full px-6 py-3 text-sm font-bold text-white shadow-lg" style={{ background: spec.theme.accent }}>{c.cta || 'Get in touch'}</a></div><div className="min-h-64 rounded-[2rem] border border-black/5 bg-white p-4 shadow-2xl"><div className="h-full min-h-56 rounded-[1.5rem] p-8" style={{ background: `linear-gradient(135deg, ${spec.theme.primary}, ${spec.theme.accent})` }}><div className="h-full rounded-2xl border border-white/20 bg-white/10 p-6 backdrop-blur"><div className="text-sm font-medium text-white/70">{spec.template.name}</div><div className="mt-16 text-2xl font-bold text-white">A polished digital presence.</div></div></div></div></div></Container></Section>; }
export function About({ spec }: SectionProps) { const c = spec.content.about as { title: string; body: string }; return <Section id="about"><Container><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: spec.theme.accent }}>About</p><h2 className="mt-3 text-3xl font-bold text-slate-950 md:text-4xl">{c.title}</h2><p className="mt-5 text-lg leading-8 text-slate-600">{c.body}</p></div></Container></Section>; }
export function Services({ spec }: SectionProps) { const c = spec.content.services as { items: string[] }; return <Section id="services" className="bg-slate-50"><Container><h2 className="text-3xl font-bold text-slate-950">Services</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{c.items.map((item, i) => <article key={`${item}-${i}`} className="rounded-3xl border border-black/5 bg-white p-7 shadow-sm"><div className="mb-8 grid h-10 w-10 place-items-center rounded-xl text-sm font-bold text-white" style={{ background: spec.theme.accent }}>0{i + 1}</div><h3 className="font-bold text-slate-950">{item}</h3><p className="mt-3 text-sm leading-6 text-slate-500">A tailored solution designed around your business goals.</p></article>)}</div></Container></Section>; }
export function Products({ spec }: SectionProps) { const c = spec.content.products as { items: string[] }; return <Section id="products"><Container><h2 className="text-3xl font-bold text-slate-950">Products</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{c.items.map((item, i) => <div key={`${item}-${i}`} className="rounded-3xl p-7" style={{ background: spec.theme.surface }}><div className="h-32 rounded-2xl bg-black/5" /><h3 className="mt-5 font-bold text-slate-950">{item}</h3></div>)}</div></Container></Section>; }
export function Gallery({ spec }: SectionProps) { const c = spec.content.gallery as { images: string[] }; return <Section id="gallery" className="bg-slate-50"><Container><h2 className="text-3xl font-bold text-slate-950">Gallery</h2>{c.images.length ? <div className="mt-8 grid gap-4 sm:grid-cols-2 md:grid-cols-3">{c.images.map((image, i) => <img key={`${image}-${i}`} src={image} alt="" className="h-56 w-full rounded-3xl object-cover" />)}</div> : <p className="mt-6 text-slate-500">No gallery images have been added yet.</p>}</Container></Section>; }
export function Testimonials({ spec }: SectionProps) { const c = spec.content.testimonials as { items: { quote: string; author: string }[] }; return <Section id="testimonials"><Container><h2 className="text-3xl font-bold text-slate-950">What people say</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{c.items.map((item, i) => <blockquote key={i} className="rounded-3xl border border-black/5 bg-white p-7 shadow-sm"><p className="text-lg leading-8 text-slate-700">“{item.quote}”</p><footer className="mt-5 text-sm font-semibold text-slate-500">{item.author}</footer></blockquote>)}</div></Container></Section>; }
export function Pricing({ spec }: SectionProps) { const c = spec.content.pricing as { items: { name?: string; price?: string }[] }; return <Section id="pricing" className="bg-slate-50"><Container><h2 className="text-3xl font-bold text-slate-950">Pricing</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{(c.items.length ? c.items : [{ name: 'Custom', price: 'Let’s talk' }]).map((item, i) => <div key={i} className="rounded-3xl bg-white p-7 shadow-sm"><h3 className="font-bold">{item.name}</h3><div className="mt-5 text-2xl font-black" style={{ color: spec.theme.accent }}>{item.price}</div></div>)}</div></Container></Section>; }
export function FAQ({ spec }: SectionProps) { const c = spec.content.faq as { items: { question: string; answer: string }[] }; return <Section id="faq"><Container><h2 className="text-3xl font-bold text-slate-950">FAQ</h2><div className="mt-8 space-y-3">{c.items.map((item, i) => <details key={i} className="rounded-2xl border border-black/5 bg-white p-5"><summary className="cursor-pointer font-semibold text-slate-900">{item.question}</summary><p className="mt-3 leading-7 text-slate-600">{item.answer}</p></details>)}</div></Container></Section>; }
export function Contact({ spec }: SectionProps) { const c = spec.content.contact as { phone: string; email: string; whatsapp: string }; return <Section id="contact" className="text-white" style={{ background: spec.theme.primary }}><Container><h2 className="text-3xl font-bold">Let’s connect</h2><div className="mt-6 flex flex-wrap gap-3 text-sm">{[c.phone, c.email, c.whatsapp].filter(Boolean).map((value) => <span key={value} className="rounded-full border border-white/15 bg-white/10 px-4 py-2">{value}</span>)}</div></Container></Section>; }
export function Location({ spec }: SectionProps) { const c = spec.content.location as { address: string }; if (!c.address?.trim()) return null; return <Section id="location"><Container><h2 className="text-3xl font-bold text-slate-950">Visit us</h2><p className="mt-4 text-slate-600">{c.address}</p></Container></Section>; }
export function Footer({ spec }: SectionProps) { return <footer id="footer" className="border-t border-black/5 bg-white px-6 py-10"><Container><div className="flex flex-col justify-between gap-3 text-sm text-slate-500 md:flex-row"><span>© {new Date().getFullYear()} {spec.business.businessName}</span>{spec.attribution.enabled && <span>{spec.attribution.label}</span>}</div></Container></footer>; }
